import React from "react";

const config = {
  ROMS: {
    owlia: {
      name: "The Legends of Owlia",
      url: "https://cdn.jsdelivr.net/gh/bfirsh/jsnes-roms@master/owlia.nes"
    },
    nomolos: {
      name: "Nomolos: Storming the Catsle",
      url: "https://cdn.jsdelivr.net/gh/bfirsh/jsnes-roms@master/nomolos.nes"
    },
    croom: {
      name: "Concentration Room",
      url:
        "https://cdn.jsdelivr.net/gh/bfirsh/jsnes-roms@master/croom/croom.nes"
    },
    lj65: {
      name: "LJ65",
      url: "https://cdn.jsdelivr.net/gh/bfirsh/jsnes-roms@master/lj65/lj65.nes"
    },
    mario: {
      name: "Mario",
      url: "https://raw.githubusercontent.com/thanhtung249/demo/master/Super%20Mario%20Bros.%20(World).nes"
    },
    TenYardFight: {
      name: "10-Yard Fight",
      url: "https://github.com/dientu4nut/NES/blob/master/10-Yard%20Fight%20(U)%20.nes"
    },
    1942: { name: "1942", url: "https://github.com/dientu4nut/NES/blob/master/1942%20(JU).nes" },
    TheBattleofMidway: { name: "1943 - The Battle of Midway", url: "https://github.com/dientu4nut/NES/blob/master/1943%20-%20The%20Battle%20of%20Midway%20(U)%20.nes" },
    BattlesofWorldRunnerThe: { name: "3-D Battles of World Runner The", url: "https://github.com/dientu4nut/NES/blob/master/3-D%20Battles%20of%20World%20Runner%20The%20(U)%20.nes" },
    720: { name: "720", url: "https://github.com/dientu4nut/NES/blob/master/720%20(U)%20.nes" },
    EightEyes: { name: "8 Eyes", url: "https://github.com/dientu4nut/NES/blob/master/8%20Eyes%20(U)%20.nes" },
    AbadoxTheDeadlyInnerWar: { name: "Abadox - The Deadly Inner War", url: "https://github.com/dientu4nut/NES/blob/master/Abadox%20-%20The%20Deadly%20Inner%20War%20(U)%20.nes" },
    Action52ActiveEnterprises: { name: "Action 52 (Active Enterprises)", url: "https://github.com/dientu4nut/NES/blob/master/Action%2052%20(Active%20Enterprises).nes" },
    AddamsFamilyThe: { name: "Addams Family The", url: "https://github.com/dientu4nut/NES/blob/master/Addams%20Family%20The%20(U)%20.nes" },
    AddamsFamilyThePugsleysScavengerHunt: { name: "Addams Family The - Pugsley s Scavenger Hunt", url: "https://github.com/dientu4nut/NES/blob/master/Addams%20Family%20The%20-%20Pugsley%20s%20Scavenger%20Hunt%20(U)%20.nes" },
    AdvancedDungeonsDragonsDragonStrike: { name: "Advanced Dungeons & Dragons - Dragon Strike", url: "https://github.com/dientu4nut/NES/blob/master/Advanced%20Dungeons%20%26%20Dragons%20-%20Dragon%20Strike%20(U)%20.nes" },
    AdvancedDungeonsDragonsHeroesoftheLance: { name: "Advanced Dungeons & Dragons - Heroes of the Lance", url: "https://github.com/dientu4nut/NES/blob/master/Advanced%20Dungeons%20%26%20Dragons%20-%20Heroes%20of%20the%20Lance%20(U)%20.nes" },
    AdvancedDungeonsDragonsHillsfar: { name: "Advanced Dungeons & Dragons - Hillsfar", url: "https://github.com/dientu4nut/NES/blob/master/Advanced%20Dungeons%20%26%20Dragons%20-%20Hillsfar%20(U)%20.nes" },
    AdvancedDungeonsDragonsPoolofRadiance: { name: "Advanced Dungeons & Dragons - Pool of Radiance", url: "https://github.com/dientu4nut/NES/blob/master/Advanced%20Dungeons%20%26%20Dragons%20-%20Pool%20of%20Radiance%20(U)%20.nes" },
    AdventuresintheMagicKingdom: { name: "Adventures in the Magic Kingdom", url: "https://github.com/dientu4nut/NES/blob/master/Adventures%20in%20the%20Magic%20Kingdom%20(U)%20.nes" },
    AdventuresofBayouBillyThe: { name: "Adventures of Bayou Billy The", url: "https://github.com/dientu4nut/NES/blob/master/Adventures%20of%20Bayou%20Billy%20The%20(U)%20.nes" },
    AdventuresofDinoRikiThe: { name: "Adventures of Dino Riki The", url: "https://github.com/dientu4nut/NES/blob/master/Adventures%20of%20Dino%20Riki%20The%20(U)%20.nes" },
    AdventuresofGilligansIslandThe: { name: "Adventures of Gilligan s Island The", url: "https://github.com/dientu4nut/NES/blob/master/Adventures%20of%20Gilligan%20s%20Island%20The%20(U)%20.nes" },
    AdventuresofLolo: { name: "Adventures of Lolo", url: "https://github.com/dientu4nut/NES/blob/master/Adventures%20of%20Lolo%20(U)%20.nes" },
    AdventuresofLolo2: { name: "Adventures of Lolo 2", url: "https://github.com/dientu4nut/NES/blob/master/Adventures%20of%20Lolo%202%20(U)%20.nes" },
    AdventuresofLolo3: { name: "Adventures of Lolo 3", url: "https://github.com/dientu4nut/NES/blob/master/Adventures%20of%20Lolo%203%20(U)%20.nes" },
    AdventuresofRadGravityThe: { name: "Adventures of Rad Gravity The", url: "https://github.com/dientu4nut/NES/blob/master/Adventures%20of%20Rad%20Gravity%20The%20(U)%20.nes" },
    AdventuresofRockyandBullwinkleandFriendsThe: { name: "Adventures of Rocky and Bullwinkle and Friends The", url: "https://github.com/dientu4nut/NES/blob/master/Adventures%20of%20Rocky%20and%20Bullwinkle%20and%20Friends%20The%20(U)%20.nes" },
    AdventuresofTomSawyer: { name: "Adventures of Tom Sawyer", url: "https://github.com/dientu4nut/NES/blob/master/Adventures%20of%20Tom%20Sawyer%20(U)%20.nes" },
    AirFortress: { name: "Air Fortress", url: "https://github.com/dientu4nut/NES/blob/master/Air%20Fortress%20(U)%20.nes" },
    Airwolf: { name: "Airwolf", url: "https://github.com/dientu4nut/NES/blob/master/Airwolf%20(U)%20.nes" },
    AlUnserJrTurboRacing: { name: "Al Unser Jr. Turbo Racing", url: "https://github.com/dientu4nut/NES/blob/master/Al%20Unser%20Jr.%20Turbo%20Racing%20(U)%20.nes" },
    Aladdin: { name: "Aladdin ", url: "https://github.com/dientu4nut/NES/blob/master/Aladdin%20(E)%20.nes" },
    AlfredChicken: { name: "Alfred Chicken", url: "https://github.com/dientu4nut/NES/blob/master/Alfred%20Chicken%20(U)%20.nes" },
    Alien3: { name: "Alien 3", url: "https://github.com/dientu4nut/NES/blob/master/Alien%203%20(U)%20.nes" },
    AllProBasketball: { name: "All-Pro Basketball", url: "https://github.com/dientu4nut/NES/blob/master/All-Pro%20Basketball%20(U)%20.nes" },
    AlphaMission: { name: "Alpha Mission", url: "https://github.com/dientu4nut/NES/blob/master/Alpha%20Mission%20(U)%20.nes" },
    Amagon: { name: "Amagon", url: "https://github.com/dientu4nut/NES/blob/master/Amagon%20(U)%20.nes" },
    AmericanGladiators: { name: "American Gladiators", url: "https://github.com/dientu4nut/NES/blob/master/American%20Gladiators%20(U)%20.nes" },
    Anticipation: { name: "Anticipation", url: "https://github.com/dientu4nut/NES/blob/master/Anticipation%20(U)%20.nes" },
    ArchRivalsABasketbrawl: { name: "Arch Rivals - A Basketbrawl ", url: "https://github.com/dientu4nut/NES/blob/master/Arch%20Rivals%20-%20A%20Basketbrawl%20%20(U)%20.nes" },
    Archon: { name: "Archon", url: "https://github.com/dientu4nut/NES/blob/master/Archon%20(U)%20.nes" },
    Arkanoid: { name: "Arkanoid", url: "https://github.com/dientu4nut/NES/blob/master/Arkanoid%20(U)%20.nes" },
    ArkistasRing: { name: "Arkista s Ring", url: "https://github.com/dientu4nut/NES/blob/master/Arkista%20s%20Ring%20(U)%20.nes" },
    Asterix: { name: "Asterix ", url: "https://github.com/dientu4nut/NES/blob/master/Asterix%20(E)%20.nes" },
    Astyanax: { name: "Astyanax", url: "https://github.com/dientu4nut/NES/blob/master/Astyanax%20(U)%20.nes" },
    Athena: { name: "Athena", url: "https://github.com/dientu4nut/NES/blob/master/Athena%20(U)%20.nes" },
    AthleticWorld: { name: "Athletic World", url: "https://github.com/dientu4nut/NES/blob/master/Athletic%20World%20(U)%20.nes" },
    AttackoftheKillerTomatoes: { name: "Attack of the Killer Tomatoes", url: "https://github.com/dientu4nut/NES/blob/master/Attack%20of%20the%20Killer%20Tomatoes%20(U)%20.nes" },
    AussieRulesFootyA: { name: "Aussie Rules Footy (A) ", url: "https://github.com/dientu4nut/NES/blob/master/Aussie%20Rules%20Footy%20(A)%20.nes" },
    BacktotheFuture: { name: "Back to the Future", url: "https://github.com/dientu4nut/NES/blob/master/Back%20to%20the%20Future%20(U)%20.nes" },
    BacktotheFuturePartIIIII: { name: "Back to the Future Part II & III", url: "https://github.com/dientu4nut/NES/blob/master/Back%20to%20the%20Future%20Part%20II%20%26%20III%20(U)%20.nes" },
    BadDudes: { name: "Bad Dudes", url: "https://github.com/dientu4nut/NES/blob/master/Bad%20Dudes%20(U)%20.nes" },
    BadNewsBaseball: { name: "Bad News Baseball", url: "https://github.com/dientu4nut/NES/blob/master/Bad%20News%20Baseball%20(U)%20.nes" },
    BadStreetBrawler: { name: "Bad Street Brawler", url: "https://github.com/dientu4nut/NES/blob/master/Bad%20Street%20Brawler%20(U)%20.nes" },
    BalloonFight: { name: "Balloon Fight", url: "https://github.com/dientu4nut/NES/blob/master/Balloon%20Fight%20(U)%20.nes" },
    BandaiGolfChallengePebbleBeach: { name: "Bandai Golf - Challenge Pebble Beach", url: "https://github.com/dientu4nut/NES/blob/master/Bandai%20Golf%20-%20Challenge%20Pebble%20Beach%20(U)%20.nes" },
    BanditKingsofAncientChina: { name: "Bandit Kings of Ancient China", url: "https://github.com/dientu4nut/NES/blob/master/Bandit%20Kings%20of%20Ancient%20China%20(U)%20.nes" },
    BardsTaleTheTalesoftheUnknown: { name: "Bard s Tale The - Tales of the Unknown", url: "https://github.com/dientu4nut/NES/blob/master/Bard%20s%20Tale%20The%20-%20Tales%20of%20the%20Unknown%20(U)%20.nes" },
    BarkerBillsTrickShooting: { name: "Barker Bill s Trick Shooting", url: "https://github.com/dientu4nut/NES/blob/master/Barker%20Bill%20s%20Trick%20Shooting%20(U)%20.nes" },
    BaseWars: { name: "Base Wars", url: "https://github.com/dientu4nut/NES/blob/master/Base%20Wars%20(U)%20.nes" },
    Baseball: { name: "Baseball", url: "https://github.com/dientu4nut/NES/blob/master/Baseball%20(U)%20.nes" },
    BaseballSimulator1000: { name: "Baseball Simulator 1.000", url: "https://github.com/dientu4nut/NES/blob/master/Baseball%20Simulator%201.000%20(U)%20.nes" },
    BaseballStars: { name: "Baseball Stars", url: "https://github.com/dientu4nut/NES/blob/master/Baseball%20Stars%20(U)%20.nes" },
    BaseballStarsII: { name: "Baseball Stars II", url: "https://github.com/dientu4nut/NES/blob/master/Baseball%20Stars%20II%20(U)%20.nes" },
    BasesLoaded3: { name: "Bases Loaded 3", url: "https://github.com/dientu4nut/NES/blob/master/Bases%20Loaded%203%20(U)%20.nes" },
    BasesLoaded4: { name: "Bases Loaded 4", url: "https://github.com/dientu4nut/NES/blob/master/Bases%20Loaded%204%20(U)%20.nes" },
    BasesLoadedII: { name: "Bases Loaded II", url: "https://github.com/dientu4nut/NES/blob/master/Bases%20Loaded%20II%20(U)%20.nes" },
    Batman: { name: "Batman", url: "https://github.com/dientu4nut/NES/blob/master/Batman%20(U)%20.nes" },
    BatmanReturnoftheJoker: { name: "Batman - Return of the Joker", url: "https://github.com/dientu4nut/NES/blob/master/Batman%20-%20Return%20of%20the%20Joker%20(U)%20.nes" },
    BatmanReturns: { name: "Batman Returns", url: "https://github.com/dientu4nut/NES/blob/master/Batman%20Returns%20(U)%20.nes" },
    BattleChess: { name: "Battle Chess", url: "https://github.com/dientu4nut/NES/blob/master/Battle%20Chess%20(U)%20.nes" },
    BattleTank: { name: "Battle Tank", url: "https://github.com/dientu4nut/NES/blob/master/Battle%20Tank%20(U)%20.nes" },
    BattleofOlympusThe: { name: "Battle of Olympus The", url: "https://github.com/dientu4nut/NES/blob/master/Battle%20of%20Olympus%20The%20(U)%20.nes" },
    Battleship: { name: "Battleship", url: "https://github.com/dientu4nut/NES/blob/master/Battleship%20(U)%20.nes" },
    BattletoadsDoubleDragonTheUltimateTeam: { name: "Battletoads & Double Dragon - The Ultimate Team", url: "https://github.com/dientu4nut/NES/blob/master/Battletoads%20%26%20Double%20Dragon%20-%20The%20Ultimate%20Team%20(U)%20.nes" },
    Battletoads: { name: "Battletoads", url: "https://github.com/dientu4nut/NES/blob/master/Battletoads%20(U)%20.nes" },
    BeautyandtheBeast: { name: "Beauty and the Beast ", url: "https://github.com/dientu4nut/NES/blob/master/Beauty%20and%20the%20Beast%20(E)%20.nes" },
    Beetlejuice: { name: "Beetlejuice", url: "https://github.com/dientu4nut/NES/blob/master/Beetlejuice%20(U)%20.nes" },
    BestoftheBestChampionshipKarate: { name: "Best of the Best - Championship Karate", url: "https://github.com/dientu4nut/NES/blob/master/Best%20of%20the%20Best%20-%20Championship%20Karate%20(U)%20.nes" },
    BigBirdsHideSpeak: { name: "Big Bird s Hide & Speak", url: "https://github.com/dientu4nut/NES/blob/master/Big%20Bird%20s%20Hide%20%26%20Speak%20(U)%20.nes" },
    Bigfoot: { name: "Bigfoot", url: "https://github.com/dientu4nut/NES/blob/master/Bigfoot%20(U)%20.nes" },
    BillTedsExcellentVideoGameAdventure: { name: "Bill & Ted s Excellent Video Game Adventure", url: "https://github.com/dientu4nut/NES/blob/master/Bill%20%26%20Ted%20s%20Excellent%20Video%20Game%20Adventure%20(U)%20.nes" },
    BillElliottsNASCARChallenge: { name: "Bill Elliott s NASCAR Challenge", url: "https://github.com/dientu4nut/NES/blob/master/Bill%20Elliott%20s%20NASCAR%20Challenge%20(U)%20.nes" },
    BionicCommando: { name: "Bionic Commando", url: "https://github.com/dientu4nut/NES/blob/master/Bionic%20Commando%20(U)%20.nes" },
    BlackBassUSAThe: { name: "Black Bass USA The", url: "https://github.com/dientu4nut/NES/blob/master/Black%20Bass%20USA%20The%20(U)%20.nes" },
    BladesofSteel: { name: "Blades of Steel", url: "https://github.com/dientu4nut/NES/blob/master/Blades%20of%20Steel%20(U)%20.nes" },
    BlasterMaster: { name: "Blaster Master", url: "https://github.com/dientu4nut/NES/blob/master/Blaster%20Master%20(U)%20.nes" },
    BlueMarlinThe: { name: "Blue Marlin The", url: "https://github.com/dientu4nut/NES/blob/master/Blue%20Marlin%20The%20(U)%20.nes" },
    BluesBrothersThe: { name: "Blues Brothers The", url: "https://github.com/dientu4nut/NES/blob/master/Blues%20Brothers%20The%20(U)%20.nes" },
    BoJacksonBaseball: { name: "Bo Jackson Baseball", url: "https://github.com/dientu4nut/NES/blob/master/Bo%20Jackson%20Baseball%20(U)%20.nes" },
    Bomberman: { name: "Bomberman", url: "https://github.com/dientu4nut/NES/blob/master/Bomberman%20(U)%20.nes" },
    BombermanII: { name: "Bomberman II", url: "https://github.com/dientu4nut/NES/blob/master/Bomberman%20II%20(U)%20.nes" },
    BonksAdventure: { name: "Bonk s Adventure", url: "https://github.com/dientu4nut/NES/blob/master/Bonk%20s%20Adventure%20(U)%20.nes" },
    BoulderDash: { name: "Boulder Dash", url: "https://github.com/dientu4nut/NES/blob/master/Boulder%20Dash%20(U)%20.nes" },
    BoyandHisBlobATroubleonBlobolonia: { name: "Boy and His Blob A - Trouble on Blobolonia", url: "https://github.com/dientu4nut/NES/blob/master/Boy%20and%20His%20Blob%20A%20-%20Trouble%20on%20Blobolonia%20(U)%20.nes" },
    BramStokersDracula: { name: "Bram Stoker s Dracula", url: "https://github.com/dientu4nut/NES/blob/master/Bram%20Stoker%20s%20Dracula%20(U)%20.nes" },
    BreakTimeTheNationalPoolTour: { name: "Break Time - The National Pool Tour", url: "https://github.com/dientu4nut/NES/blob/master/Break%20Time%20-%20The%20National%20Pool%20Tour%20(U)%20.nes" },
    BreakThru: { name: "BreakThru", url: "https://github.com/dientu4nut/NES/blob/master/BreakThru%20(U)%20.nes" },
    BubbleBobble: { name: "Bubble Bobble", url: "https://github.com/dientu4nut/NES/blob/master/Bubble%20Bobble%20(U)%20.nes" },
    BubbleBobblePart2: { name: "Bubble Bobble Part 2", url: "https://github.com/dientu4nut/NES/blob/master/Bubble%20Bobble%20Part%202%20(U)%20.nes" },
    BuckyOHare: { name: "Bucky O Hare", url: "https://github.com/dientu4nut/NES/blob/master/Bucky%20O%20Hare%20(U)%20.nes" },
    BugsBunnyBirthdayBlowoutThe: { name: "Bugs Bunny Birthday Blowout The", url: "https://github.com/dientu4nut/NES/blob/master/Bugs%20Bunny%20Birthday%20Blowout%20The%20(U)%20.nes" },
    BugsBunnyCrazyCastleThe: { name: "Bugs Bunny Crazy Castle The", url: "https://github.com/dientu4nut/NES/blob/master/Bugs%20Bunny%20Crazy%20Castle%20The%20(U)%20.nes" },
    BumpnJump: { name: "Bump n Jump", url: "https://github.com/dientu4nut/NES/blob/master/Bump%20n%20Jump%20(U)%20.nes" },
    BuraiFighter: { name: "Burai Fighter", url: "https://github.com/dientu4nut/NES/blob/master/Burai%20Fighter%20(U)%20.nes" },
    BurgerTime: { name: "BurgerTime", url: "https://github.com/dientu4nut/NES/blob/master/BurgerTime%20(U)%20.nes" },
    Cabal: { name: "Cabal", url: "https://github.com/dientu4nut/NES/blob/master/Cabal%20(U)%20.nes" },
    CaesarsPalace: { name: "Caesars Palace", url: "https://github.com/dientu4nut/NES/blob/master/Caesars%20Palace%20(U)%20.nes" },
    CaliforniaGames: { name: "California Games", url: "https://github.com/dientu4nut/NES/blob/master/California%20Games%20(U)%20.nes" },
    CaptainAmericaandTheAvengers: { name: "Captain America and The Avengers", url: "https://github.com/dientu4nut/NES/blob/master/Captain%20America%20and%20The%20Avengers%20(U)%20.nes" },
    CaptainPlanetandThePlaneteers: { name: "Captain Planet and The Planeteers", url: "https://github.com/dientu4nut/NES/blob/master/Captain%20Planet%20and%20The%20Planeteers%20(U)%20.nes" },
    CasinoKid: { name: "Casino Kid", url: "https://github.com/dientu4nut/NES/blob/master/Casino%20Kid%20(U)%20.nes" },
    CasinoKid2: { name: "Casino Kid 2", url: "https://github.com/dientu4nut/NES/blob/master/Casino%20Kid%202%20(U)%20.nes" },
    Castelian: { name: "Castelian", url: "https://github.com/dientu4nut/NES/blob/master/Castelian%20(U)%20.nes" },
    CastleofDragon: { name: "Castle of Dragon", url: "https://github.com/dientu4nut/NES/blob/master/Castle%20of%20Dragon%20(U)%20.nes" },
    Castlequest: { name: "Castlequest", url: "https://github.com/dientu4nut/NES/blob/master/Castlequest%20(U)%20.nes" },
    CastlevaniaU: { name: "Castlevania (U)", url: "https://github.com/dientu4nut/NES/blob/master/Castlevania%20(U).nes" },
    CastlevaniaIISimonsQuest: { name: "Castlevania II - Simon s Quest", url: "https://github.com/dientu4nut/NES/blob/master/Castlevania%20II%20-%20Simon%20s%20Quest%20(U)%20.nes" },
    CastlevaniaIIIDraculasCurse: { name: "Castlevania III - Dracula s Curse", url: "https://github.com/dientu4nut/NES/blob/master/Castlevania%20III%20-%20Dracula%20s%20Curse%20(U)%20.nes" },
    CavemanGames: { name: "Caveman Games", url: "https://github.com/dientu4nut/NES/blob/master/Caveman%20Games%20(U)%20.nes" },
    ChampionshipBowling: { name: "Championship Bowling", url: "https://github.com/dientu4nut/NES/blob/master/Championship%20Bowling%20(U)%20.nes" },
    ChampionshipPool: { name: "Championship Pool", url: "https://github.com/dientu4nut/NES/blob/master/Championship%20Pool%20(U)%20.nes" },
    ChampionshipRally: { name: "Championship Rally ", url: "https://github.com/dientu4nut/NES/blob/master/Championship%20Rally%20(E)%20.nes" },
    CheetahMenIIActiveEnterprises: { name: "Cheetah Men II (Active Enterprises)", url: "https://github.com/dientu4nut/NES/blob/master/Cheetah%20Men%20II%20(Active%20Enterprises).nes" },
    ChipnDaleRescueRangers: { name: "Chip  n Dale Rescue Rangers", url: "https://github.com/dientu4nut/NES/blob/master/Chip%20%20n%20Dale%20Rescue%20Rangers%20(U)%20.nes" },
    ChipnDaleRescueRangers2: { name: "Chip  n Dale Rescue Rangers 2", url: "https://github.com/dientu4nut/NES/blob/master/Chip%20%20n%20Dale%20Rescue%20Rangers%202%20(U)%20.nes" },
    ChubbyCherub: { name: "Chubby Cherub", url: "https://github.com/dientu4nut/NES/blob/master/Chubby%20Cherub%20(U)%20.nes" },
    CircusCaper: { name: "Circus Caper", url: "https://github.com/dientu4nut/NES/blob/master/Circus%20Caper%20(U)%20.nes" },
    CircusCharlieJ: { name: "Circus Charlie (J)", url: "https://github.com/dientu4nut/NES/blob/master/Circus%20Charlie%20(J).nes" },
    CityConnection: { name: "City Connection", url: "https://github.com/dientu4nut/NES/blob/master/City%20Connection%20(U)%20.nes" },
    ClassicConcentration: { name: "Classic Concentration", url: "https://github.com/dientu4nut/NES/blob/master/Classic%20Concentration%20(U)%20.nes" },
    Cliffhanger: { name: "Cliffhanger", url: "https://github.com/dientu4nut/NES/blob/master/Cliffhanger%20(U)%20.nes" },
    CobraCommand: { name: "Cobra Command", url: "https://github.com/dientu4nut/NES/blob/master/Cobra%20Command%20(U)%20.nes" },
    CobraTriangle: { name: "Cobra Triangle", url: "https://github.com/dientu4nut/NES/blob/master/Cobra%20Triangle%20(U)%20.nes" },
    CodeNameViper: { name: "Code Name - Viper", url: "https://github.com/dientu4nut/NES/blob/master/Code%20Name%20-%20Viper%20(U)%20.nes" },
    ColorADinosaur: { name: "Color A Dinosaur", url: "https://github.com/dientu4nut/NES/blob/master/Color%20A%20Dinosaur%20(U)%20.nes" },
    Commando: { name: "Commando", url: "https://github.com/dientu4nut/NES/blob/master/Commando%20(U)%20.nes" },
    ConanTheMysteriesofTime: { name: "Conan - The Mysteries of Time", url: "https://github.com/dientu4nut/NES/blob/master/Conan%20-%20The%20Mysteries%20of%20Time%20(U)%20.nes" },
    Conflict: { name: "Conflict", url: "https://github.com/dientu4nut/NES/blob/master/Conflict%20(U)%20.nes" },
    ConquestoftheCrystalPalace: { name: "Conquest of the Crystal Palace", url: "https://github.com/dientu4nut/NES/blob/master/Conquest%20of%20the%20Crystal%20Palace%20(U)%20.nes" },
    ContraJEnglishPatched: { name: "Contra (J-English Patched)", url: "https://github.com/dientu4nut/NES/blob/master/Contra%20(J-English%20Patched).nes" },
    Contra: { name: "Contra", url: "https://github.com/dientu4nut/NES/blob/master/Contra%20(U)%20.nes" },
    ContraForce: { name: "Contra Force", url: "https://github.com/dientu4nut/NES/blob/master/Contra%20Force%20(U)%20.nes" },
    CoolWorld: { name: "Cool World", url: "https://github.com/dientu4nut/NES/blob/master/Cool%20World%20(U)%20.nes" },
    CowboyKid: { name: "Cowboy Kid", url: "https://github.com/dientu4nut/NES/blob/master/Cowboy%20Kid%20(U)%20.nes" },
    Crackoutp: { name: "Crackout [ p]", url: "https://github.com/dientu4nut/NES/blob/master/Crackout%20(E)%20%5B%20p%5D.nes" },
    CrashntheBoysStreetChallenge: { name: "Crash  n the Boys - Street Challenge", url: "https://github.com/dientu4nut/NES/blob/master/Crash%20%20n%20the%20Boys%20-%20Street%20Challenge%20(U)%20.nes" },
    Crystalis: { name: "Crystalis", url: "https://github.com/dientu4nut/NES/blob/master/Crystalis%20(U)%20.nes" },
    Cyberball: { name: "Cyberball", url: "https://github.com/dientu4nut/NES/blob/master/Cyberball%20(U)%20.nes" },
    CybernoidTheFightingMachine: { name: "Cybernoid - The Fighting Machine", url: "https://github.com/dientu4nut/NES/blob/master/Cybernoid%20-%20The%20Fighting%20Machine%20(U)%20.nes" },
    DanceAerobics: { name: "Dance Aerobics", url: "https://github.com/dientu4nut/NES/blob/master/Dance%20Aerobics%20(U)%20.nes" },
    DannySullivansIndyHeat: { name: "Danny Sullivan s Indy Heat", url: "https://github.com/dientu4nut/NES/blob/master/Danny%20Sullivan%20s%20Indy%20Heat%20(U)%20.nes" },
    Darkman: { name: "Darkman", url: "https://github.com/dientu4nut/NES/blob/master/Darkman%20(U)%20.nes" },
    DarkwingDuck: { name: "Darkwing Duck", url: "https://github.com/dientu4nut/NES/blob/master/Darkwing%20Duck%20(U)%20.nes" },
    DashGalaxyintheAlienAsylum: { name: "Dash Galaxy in the Alien Asylum", url: "https://github.com/dientu4nut/NES/blob/master/Dash%20Galaxy%20in%20the%20Alien%20Asylum%20(U)%20.nes" },
    DayDreaminDavey: { name: "Day Dreamin  Davey", url: "https://github.com/dientu4nut/NES/blob/master/Day%20Dreamin%20%20Davey%20(U)%20.nes" },
    DaysofThunder: { name: "Days of Thunder", url: "https://github.com/dientu4nut/NES/blob/master/Days%20of%20Thunder%20(U)%20.nes" },
    DeadlyTowers: { name: "Deadly Towers", url: "https://github.com/dientu4nut/NES/blob/master/Deadly%20Towers%20(U)%20.nes" },
    DefenderII: { name: "Defender II", url: "https://github.com/dientu4nut/NES/blob/master/Defender%20II%20(U)%20.nes" },
    DefenderoftheCrown: { name: "Defender of the Crown", url: "https://github.com/dientu4nut/NES/blob/master/Defender%20of%20the%20Crown%20(U)%20.nes" },
    DefendersofDynatronCity: { name: "Defenders of Dynatron City", url: "https://github.com/dientu4nut/NES/blob/master/Defenders%20of%20Dynatron%20City%20(U)%20.nes" },
    DejaVu: { name: "Deja Vu", url: "https://github.com/dientu4nut/NES/blob/master/Deja%20Vu%20(U)%20.nes" },
    DemonSword: { name: "Demon Sword", url: "https://github.com/dientu4nut/NES/blob/master/Demon%20Sword%20(U)%20.nes" },
    DesertCommander: { name: "Desert Commander", url: "https://github.com/dientu4nut/NES/blob/master/Desert%20Commander%20(U)%20.nes" },
    DestinationEarthstar: { name: "Destination Earthstar", url: "https://github.com/dientu4nut/NES/blob/master/Destination%20Earthstar%20(U)%20.nes" },
    DestinyofanEmperor: { name: "Destiny of an Emperor", url: "https://github.com/dientu4nut/NES/blob/master/Destiny%20of%20an%20Emperor%20(U)%20.nes" },
    DevilWorld: { name: "Devil World ", url: "https://github.com/dientu4nut/NES/blob/master/Devil%20World%20(E)%20.nes" },
    DickTracy: { name: "Dick Tracy", url: "https://github.com/dientu4nut/NES/blob/master/Dick%20Tracy%20(U)%20.nes" },
    DieHard: { name: "Die Hard", url: "https://github.com/dientu4nut/NES/blob/master/Die%20Hard%20(U)%20.nes" },
    DigDugIITroubleinParadise: { name: "Dig Dug II - Trouble in Paradise", url: "https://github.com/dientu4nut/NES/blob/master/Dig%20Dug%20II%20-%20Trouble%20in%20Paradise%20(U)%20.nes" },
    DiggerTheLegendoftheLostCity: { name: "Digger - The Legend of the Lost City", url: "https://github.com/dientu4nut/NES/blob/master/Digger%20-%20The%20Legend%20of%20the%20Lost%20City%20(U)%20.nes" },
    DirtyHarryTheWarAgainstDrugs: { name: "Dirty Harry - The War Against Drugs", url: "https://github.com/dientu4nut/NES/blob/master/Dirty%20Harry%20-%20The%20War%20Against%20Drugs%20(U)%20.nes" },
    DonkeyKong3: { name: "Donkey Kong 3", url: "https://github.com/dientu4nut/NES/blob/master/Donkey%20Kong%203%20(U)%20.nes" },
    DonkeyKongClassics: { name: "Donkey Kong Classics", url: "https://github.com/dientu4nut/NES/blob/master/Donkey%20Kong%20Classics%20(U)%20.nes" },
    DonkeyKongJrMath: { name: "Donkey Kong Jr. Math", url: "https://github.com/dientu4nut/NES/blob/master/Donkey%20Kong%20Jr.%20Math%20(U)%20.nes" },
    DoubleDare: { name: "Double Dare", url: "https://github.com/dientu4nut/NES/blob/master/Double%20Dare%20(U)%20.nes" },
    DoubleDragon: { name: "Double Dragon", url: "https://github.com/dientu4nut/NES/blob/master/Double%20Dragon%20(U)%20.nes" },
    DoubleDragonIIITheSacredStones: { name: "Double Dragon III - The Sacred Stones", url: "https://github.com/dientu4nut/NES/blob/master/Double%20Dragon%20III%20-%20The%20Sacred%20Stones%20(U)%20.nes" },
    DrChaos: { name: "Dr. Chaos", url: "https://github.com/dientu4nut/NES/blob/master/Dr.%20Chaos%20(U)%20.nes" },
    DrJekyllandMrHyde: { name: "Dr. Jekyll and Mr. Hyde", url: "https://github.com/dientu4nut/NES/blob/master/Dr.%20Jekyll%20and%20Mr.%20Hyde%20(U)%20.nes" },
    DrMario: { name: "Dr. Mario [!]", url: "https://github.com/dientu4nut/NES/blob/master/Dr.%20Mario%20(E)%20%5B!%5D.nes" },
    DragonFighter: { name: "Dragon Fighter", url: "https://github.com/dientu4nut/NES/blob/master/Dragon%20Fighter%20(U)%20.nes" },
    DragonPower: { name: "Dragon Power", url: "https://github.com/dientu4nut/NES/blob/master/Dragon%20Power%20(U)%20.nes" },
    DragonSpiritTheNewLegend: { name: "Dragon Spirit - The New Legend", url: "https://github.com/dientu4nut/NES/blob/master/Dragon%20Spirit%20-%20The%20New%20Legend%20(U)%20.nes" },
    DragonWarriorII: { name: "Dragon Warrior II", url: "https://github.com/dientu4nut/NES/blob/master/Dragon%20Warrior%20II%20(U)%20.nes" },
    DragonWarriorIII: { name: "Dragon Warrior III", url: "https://github.com/dientu4nut/NES/blob/master/Dragon%20Warrior%20III%20(U)%20.nes" },
    DragonWarriorIV: { name: "Dragon Warrior IV", url: "https://github.com/dientu4nut/NES/blob/master/Dragon%20Warrior%20IV%20(U)%20.nes" },
    DragonsLair: { name: "Dragon s Lair", url: "https://github.com/dientu4nut/NES/blob/master/Dragon%20s%20Lair%20(U)%20.nes" },
    DropZone: { name: "Drop Zone", url: "https://github.com/dientu4nut/NES/blob/master/Drop%20Zone%20(E).nes" },
    DuckTales: { name: "Duck Tales", url: "https://github.com/dientu4nut/NES/blob/master/Duck%20Tales%20(U)%20.nes" },
    DuckTales2: { name: "Duck Tales 2", url: "https://github.com/dientu4nut/NES/blob/master/Duck%20Tales%202%20(U)%20.nes" },
    DungeonMagicSwordoftheElements: { name: "Dungeon Magic - Sword of the Elements", url: "https://github.com/dientu4nut/NES/blob/master/Dungeon%20Magic%20-%20Sword%20of%20the%20Elements%20(U)%20.nes" },
    DustyDiamondsAllStarSoftball: { name: "Dusty Diamond s All-Star Softball", url: "https://github.com/dientu4nut/NES/blob/master/Dusty%20Diamond%20s%20All-Star%20Softball%20(U)%20.nes" },
    DynowarzTheDestructionofSpondylus: { name: "Dynowarz - The Destruction of Spondylus", url: "https://github.com/dientu4nut/NES/blob/master/Dynowarz%20-%20The%20Destruction%20of%20Spondylus%20(U)%20.nes" },
    ElevatorAction: { name: "Elevator Action", url: "https://github.com/dientu4nut/NES/blob/master/Elevator%20Action%20(U)%20.nes" },
    EliminatorBoatDuel: { name: "Eliminator Boat Duel", url: "https://github.com/dientu4nut/NES/blob/master/Eliminator%20Boat%20Duel%20(U)%20.nes" },
    Elite: { name: "Elite ", url: "https://github.com/dientu4nut/NES/blob/master/Elite%20(E)%20.nes" },
    Excitebike: { name: "Excitebike", url: "https://github.com/dientu4nut/NES/blob/master/Excitebike%20(E).nes" },
    F117AStealthFighter: { name: "F-117A Stealth Fighter", url: "https://github.com/dientu4nut/NES/blob/master/F-117A%20Stealth%20Fighter%20(U)%20.nes" },
    F15StrikeEagle: { name: "F-15 Strike Eagle", url: "https://github.com/dientu4nut/NES/blob/master/F-15%20Strike%20Eagle%20(U)%20.nes" },
    FamilyFeud: { name: "Family Feud", url: "https://github.com/dientu4nut/NES/blob/master/Family%20Feud%20(U)%20.nes" },
    FariaAWorldofMysteryDanger: { name: "Faria - A World of Mystery & Danger ", url: "https://github.com/dientu4nut/NES/blob/master/Faria%20-%20A%20World%20of%20Mystery%20%26%20Danger%20%20(U)%20.nes" },
    FelixtheCat: { name: "Felix the Cat", url: "https://github.com/dientu4nut/NES/blob/master/Felix%20the%20Cat%20(U)%20.nes" },
    FerrariGrandPrixChallenge: { name: "Ferrari - Grand Prix Challenge", url: "https://github.com/dientu4nut/NES/blob/master/Ferrari%20-%20Grand%20Prix%20Challenge%20(U)%20.nes" },
    FestersQuest: { name: "Fester s Quest", url: "https://github.com/dientu4nut/NES/blob/master/Fester%20s%20Quest%20(U)%20.nes" },
    FinalFantasy: { name: "Final Fantasy", url: "https://github.com/dientu4nut/NES/blob/master/Final%20Fantasy%20(U)%20.nes" },
    FirenIce: { name: "Fire  n Ice", url: "https://github.com/dientu4nut/NES/blob/master/Fire%20%20n%20Ice%20(U)%20.nes" },
    FirehouseRescue: { name: "Firehouse Rescue", url: "https://github.com/dientu4nut/NES/blob/master/Firehouse%20Rescue%20(U)%20.nes" },
    FistoftheNorthStar: { name: "Fist of the North Star", url: "https://github.com/dientu4nut/NES/blob/master/Fist%20of%20the%20North%20Star%20(U)%20.nes" },
    FlightoftheIntruder: { name: "Flight of the Intruder", url: "https://github.com/dientu4nut/NES/blob/master/Flight%20of%20the%20Intruder%20(U)%20.nes" },
    FlintstonesTheTheRescueofDinoHoppy: { name: "Flintstones The - The Rescue of Dino & Hoppy", url: "https://github.com/dientu4nut/NES/blob/master/Flintstones%20The%20-%20The%20Rescue%20of%20Dino%20%26%20Hoppy%20(U)%20.nes" },
    FlintstonesTheTheSurpriseatDinosaurPeak: { name: "Flintstones The - The Surprise at Dinosaur Peak ", url: "https://github.com/dientu4nut/NES/blob/master/Flintstones%20The%20-%20The%20Surprise%20at%20Dinosaur%20Peak%20%20(U)%20.nes" },
    FlyingDragonTheSecretScroll: { name: "Flying Dragon - The Secret Scroll", url: "https://github.com/dientu4nut/NES/blob/master/Flying%20Dragon%20-%20The%20Secret%20Scroll%20(U)%20.nes" },
    FlyingWarriors: { name: "Flying Warriors", url: "https://github.com/dientu4nut/NES/blob/master/Flying%20Warriors%20(U)%20.nes" },
    Formula1Sensation: { name: "Formula 1 Sensation ", url: "https://github.com/dientu4nut/NES/blob/master/Formula%201%20Sensation%20(E)%20.nes" },
    FormulaOneBuiltToWin: { name: "Formula One - Built To Win", url: "https://github.com/dientu4nut/NES/blob/master/Formula%20One%20-%20Built%20To%20Win%20(U)%20.nes" },
    FrankensteinTheMonsterReturns: { name: "Frankenstein - The Monster Returns", url: "https://github.com/dientu4nut/NES/blob/master/Frankenstein%20-%20The%20Monster%20Returns%20(U)%20.nes" },
    FreedomForce: { name: "Freedom Force", url: "https://github.com/dientu4nut/NES/blob/master/Freedom%20Force%20(U)%20.nes" },
    Fridaythe13th: { name: "Friday the 13th", url: "https://github.com/dientu4nut/NES/blob/master/Friday%20the%2013th%20(U)%20.nes" },
    FunHouse: { name: "Fun House", url: "https://github.com/dientu4nut/NES/blob/master/Fun%20House%20(U)%20.nes" },
    GIJoe: { name: "G.I. Joe", url: "https://github.com/dientu4nut/NES/blob/master/G.I.%20Joe%20(U)%20.nes" },
    GIJoeTheAtlantisFactor: { name: "G.I. Joe - The Atlantis Factor", url: "https://github.com/dientu4nut/NES/blob/master/G.I.%20Joe%20-%20The%20Atlantis%20Factor%20(U)%20.nes" },
    Galaxy5000: { name: "Galaxy 5000", url: "https://github.com/dientu4nut/NES/blob/master/Galaxy%205000%20(U)%20.nes" },
    Gauntlet: { name: "Gauntlet", url: "https://github.com/dientu4nut/NES/blob/master/Gauntlet%20(U)%20.nes" },
    GauntletII: { name: "Gauntlet II", url: "https://github.com/dientu4nut/NES/blob/master/Gauntlet%20II%20(U)%20.nes" },
    Gemfire: { name: "Gemfire", url: "https://github.com/dientu4nut/NES/blob/master/Gemfire%20(U)%20.nes" },
    GenghisKhan: { name: "Genghis Khan", url: "https://github.com/dientu4nut/NES/blob/master/Genghis%20Khan%20(U)%20.nes" },
    GeorgeForemansKOBoxing: { name: "George Foreman s KO Boxing", url: "https://github.com/dientu4nut/NES/blob/master/George%20Foreman%20s%20KO%20Boxing%20(U)%20.nes" },
    Ghostbusters: { name: "Ghostbusters", url: "https://github.com/dientu4nut/NES/blob/master/Ghostbusters%20(U)%20.nes" },
    GhostbustersII: { name: "Ghostbusters II", url: "https://github.com/dientu4nut/NES/blob/master/Ghostbusters%20II%20(U)%20.nes" },
    GhostsNGoblins: { name: "Ghosts  N Goblins", url: "https://github.com/dientu4nut/NES/blob/master/Ghosts%20%20N%20Goblins%20(U)%20.nes" },
    GhoulSchool: { name: "Ghoul School", url: "https://github.com/dientu4nut/NES/blob/master/Ghoul%20School%20(U)%20.nes" },
    Goal: { name: "Goal ", url: "https://github.com/dientu4nut/NES/blob/master/Goal%20%20(U)%20.nes" },
    GoalTwo: { name: "Goal  Two", url: "https://github.com/dientu4nut/NES/blob/master/Goal%20%20Two%20(U)%20.nes" },
    GodzillaMonsterofMonsters: { name: "Godzilla - Monster of Monsters ", url: "https://github.com/dientu4nut/NES/blob/master/Godzilla%20-%20Monster%20of%20Monsters%20%20(U)%20.nes" },
    Godzilla2WaroftheMonsters: { name: "Godzilla 2 - War of the Monsters", url: "https://github.com/dientu4nut/NES/blob/master/Godzilla%202%20-%20War%20of%20the%20Monsters%20(U)%20.nes" },
    GoldMedalChallenge92: { name: "Gold Medal Challenge  92", url: "https://github.com/dientu4nut/NES/blob/master/Gold%20Medal%20Challenge%20%2092%20(U)%20.nes" },
    Golf: { name: "Golf", url: "https://github.com/dientu4nut/NES/blob/master/Golf%20(U)%20.nes" },
    GolfGrandSlam: { name: "Golf Grand Slam", url: "https://github.com/dientu4nut/NES/blob/master/Golf%20Grand%20Slam%20(U)%20.nes" },
    Golgo13TopSecretEpisode: { name: "Golgo 13 - Top Secret Episode", url: "https://github.com/dientu4nut/NES/blob/master/Golgo%2013%20-%20Top%20Secret%20Episode%20(U)%20.nes" },
    GooniesIIThe: { name: "Goonies II The", url: "https://github.com/dientu4nut/NES/blob/master/Goonies%20II%20The%20(U)%20.nes" },
    GotchaTheSport: { name: "Gotcha  - The Sport ", url: "https://github.com/dientu4nut/NES/blob/master/Gotcha%20%20-%20The%20Sport%20%20(U)%20.nes" },
    Gradius: { name: "Gradius", url: "https://github.com/dientu4nut/NES/blob/master/Gradius%20(U)%20.nes" },
    GreatWaldoSearchThe: { name: "Great Waldo Search The", url: "https://github.com/dientu4nut/NES/blob/master/Great%20Waldo%20Search%20The%20(U)%20.nes" },
    GregNormansGolfPower: { name: "Greg Norman s Golf Power", url: "https://github.com/dientu4nut/NES/blob/master/Greg%20Norman%20s%20Golf%20Power%20(U)%20.nes" },
    Gremlins2TheNewBatch: { name: "Gremlins 2 - The New Batch", url: "https://github.com/dientu4nut/NES/blob/master/Gremlins%202%20-%20The%20New%20Batch%20(U)%20.nes" },
    GuardianLegendThe: { name: "Guardian Legend The", url: "https://github.com/dientu4nut/NES/blob/master/Guardian%20Legend%20The%20(U)%20.nes" },
    GuerrillaWar: { name: "Guerrilla War", url: "https://github.com/dientu4nut/NES/blob/master/Guerrilla%20War%20(U)%20.nes" },
    Gumshoe: { name: "Gumshoe", url: "https://github.com/dientu4nut/NES/blob/master/Gumshoe%20(U)%20.nes" },
    GunNac: { name: "Gun-Nac", url: "https://github.com/dientu4nut/NES/blob/master/Gun-Nac%20(U)%20.nes" },
    GunSmoke: { name: "Gun.Smoke", url: "https://github.com/dientu4nut/NES/blob/master/Gun.Smoke%20(U)%20.nes" },
    Gyruss: { name: "Gyruss", url: "https://github.com/dientu4nut/NES/blob/master/Gyruss%20(U)%20.nes" },
    HammerinHarry: { name: "Hammerin  Harry ", url: "https://github.com/dientu4nut/NES/blob/master/Hammerin%20%20Harry%20(E)%20.nes" },
    HarlemGlobetrotters: { name: "Harlem Globetrotters", url: "https://github.com/dientu4nut/NES/blob/master/Harlem%20Globetrotters%20(U)%20.nes" },
    Hatris: { name: "Hatris", url: "https://github.com/dientu4nut/NES/blob/master/Hatris%20(U)%20.nes" },
    HeavyBarrel: { name: "Heavy Barrel", url: "https://github.com/dientu4nut/NES/blob/master/Heavy%20Barrel%20(U)%20.nes" },
    HeavyShreddin: { name: "Heavy Shreddin ", url: "https://github.com/dientu4nut/NES/blob/master/Heavy%20Shreddin%20%20(U)%20.nes" },
    HighSpeed: { name: "High Speed", url: "https://github.com/dientu4nut/NES/blob/master/High%20Speed%20(U)%20.nes" },
    HollywoodSquares: { name: "Hollywood Squares", url: "https://github.com/dientu4nut/NES/blob/master/Hollywood%20Squares%20(U)%20.nes" },
    HomeAlone2LostinNewYork: { name: "Home Alone 2 - Lost in New York", url: "https://github.com/dientu4nut/NES/blob/master/Home%20Alone%202%20-%20Lost%20in%20New%20York%20(U)%20.nes" },
    Hook: { name: "Hook", url: "https://github.com/dientu4nut/NES/blob/master/Hook%20(U)%20.nes" },
    Hoops: { name: "Hoops", url: "https://github.com/dientu4nut/NES/blob/master/Hoops%20(U)%20.nes" },
    HudsonHawk: { name: "Hudson Hawk", url: "https://github.com/dientu4nut/NES/blob/master/Hudson%20Hawk%20(U)%20.nes" },
    HudsonsAdventureIsland: { name: "Hudson s Adventure Island", url: "https://github.com/dientu4nut/NES/blob/master/Hudson%20s%20Adventure%20Island%20(U)%20.nes" },
    HudsonsAdventureIslandII: { name: "Hudson s Adventure Island II", url: "https://github.com/dientu4nut/NES/blob/master/Hudson%20s%20Adventure%20Island%20II%20(U)%20.nes" },
    HudsonsAdventureIslandIII: { name: "Hudson s Adventure Island III", url: "https://github.com/dientu4nut/NES/blob/master/Hudson%20s%20Adventure%20Island%20III%20(U)%20.nes" },
    Hydlide: { name: "Hydlide", url: "https://github.com/dientu4nut/NES/blob/master/Hydlide%20(U)%20.nes" },
    ICanRemember: { name: "I Can Remember", url: "https://github.com/dientu4nut/NES/blob/master/I%20Can%20Remember%20(U)%20.nes" },
    IceClimber: { name: "Ice Climber", url: "https://github.com/dientu4nut/NES/blob/master/Ice%20Climber%20(U)%20.nes" },
    IceHockey: { name: "Ice Hockey", url: "https://github.com/dientu4nut/NES/blob/master/Ice%20Hockey%20(U)%20.nes" },
    IkariIIITheRescue: { name: "Ikari III - The Rescue", url: "https://github.com/dientu4nut/NES/blob/master/Ikari%20III%20-%20The%20Rescue%20(U)%20.nes" },
    IkariWarriorsIIVictoryRoad: { name: "Ikari Warriors II - Victory Road", url: "https://github.com/dientu4nut/NES/blob/master/Ikari%20Warriors%20II%20-%20Victory%20Road%20(U)%20.nes" },
    ImageFight: { name: "Image Fight", url: "https://github.com/dientu4nut/NES/blob/master/Image%20Fight%20(U)%20.nes" },
    ImmortalThe: { name: "Immortal The", url: "https://github.com/dientu4nut/NES/blob/master/Immortal%20The%20(U)%20.nes" },
    ImpossibleMissionII: { name: "Impossible Mission II", url: "https://github.com/dientu4nut/NES/blob/master/Impossible%20Mission%20II%20(U)%20.nes" },
    IncredibleCrashDummiesThe: { name: "Incredible Crash Dummies The", url: "https://github.com/dientu4nut/NES/blob/master/Incredible%20Crash%20Dummies%20The%20(U)%20.nes" },
    IndianaJonesandtheLastCrusadeTaito: { name: "Indiana Jones and the Last Crusade(Taito) ", url: "https://github.com/dientu4nut/NES/blob/master/Indiana%20Jones%20and%20the%20Last%20Crusade%20(U)%20(Taito)%20.nes" },
    IndianaJonesandtheLastCrusadeUBISoft: { name: "Indiana Jones and the Last Crusade(UBI Soft) ", url: "https://github.com/dientu4nut/NES/blob/master/Indiana%20Jones%20and%20the%20Last%20Crusade%20(U)%20(UBI%20Soft)%20.nes" },
    Infiltrator: { name: "Infiltrator", url: "https://github.com/dientu4nut/NES/blob/master/Infiltrator%20(U)%20.nes" },
    InternationalCricket: { name: "International Cricket ", url: "https://github.com/dientu4nut/NES/blob/master/International%20Cricket%20(E)%20.nes" },
    IronTankTheInvasionofNormandy: { name: "Iron Tank - The Invasion of Normandy", url: "https://github.com/dientu4nut/NES/blob/master/Iron%20Tank%20-%20The%20Invasion%20of%20Normandy%20(U)%20.nes" },
    IronswordWizardsWarriorsII: { name: "Ironsword - Wizards & Warriors II", url: "https://github.com/dientu4nut/NES/blob/master/Ironsword%20-%20Wizards%20%26%20Warriors%20II%20(U)%20.nes" },
    IsolatedWarrior: { name: "Isolated Warrior", url: "https://github.com/dientu4nut/NES/blob/master/Isolated%20Warrior%20(U)%20.nes" },
    IvanIronmanStewartsSuperOffRoad: { name: "Ivan Ironman Stewart s Super Off-Road", url: "https://github.com/dientu4nut/NES/blob/master/Ivan%20Ironman%20Stewart%20s%20Super%20Off-Road%20(U)%20.nes" },
    JackNicklausGreatest18HolesofMajorChampionshipGolf: { name: "Jack Nicklaus  Greatest 18 Holes of Major Championship Golf", url: "https://github.com/dientu4nut/NES/blob/master/Jack%20Nicklaus%20%20Greatest%2018%20Holes%20of%20Major%20Championship%20Golf%20(U)%20.nes" },
    Jackal: { name: "Jackal", url: "https://github.com/dientu4nut/NES/blob/master/Jackal%20(U)%20.nes" },
    JackieChansActionKungFu: { name: "Jackie Chan s Action Kung Fu", url: "https://github.com/dientu4nut/NES/blob/master/Jackie%20Chan%20s%20Action%20Kung%20Fu%20(U)%20.nes" },
    JamesBondJr: { name: "James Bond Jr", url: "https://github.com/dientu4nut/NES/blob/master/James%20Bond%20Jr%20(U)%20.nes" },
    Jaws: { name: "Jaws", url: "https://github.com/dientu4nut/NES/blob/master/Jaws%20(U)%20.nes" },
    Jeopardy25thAnniversaryEdition: { name: "Jeopardy  25th Anniversary Edition", url: "https://github.com/dientu4nut/NES/blob/master/Jeopardy%20%2025th%20Anniversary%20Edition%20(U)%20.nes" },
    JeopardyJuniorEdition: { name: "Jeopardy  Junior Edition", url: "https://github.com/dientu4nut/NES/blob/master/Jeopardy%20%20Junior%20Edition%20(U)%20.nes" },
    JetsonsTheCogswellsCaper: { name: "Jetsons The - Cogswell s Caper ", url: "https://github.com/dientu4nut/NES/blob/master/Jetsons%20The%20-%20Cogswell%20s%20Caper%20%20(U)%20.nes" },
    JimHensonsMuppetAdventureChaosattheCarnival: { name: "Jim Henson s Muppet Adventure - Chaos at the Carnival", url: "https://github.com/dientu4nut/NES/blob/master/Jim%20Henson%20s%20Muppet%20Adventure%20-%20Chaos%20at%20the%20Carnival%20(U)%20.nes" },
    JimmyConnorsTennis: { name: "Jimmy Connor s Tennis", url: "https://github.com/dientu4nut/NES/blob/master/Jimmy%20Connor%20s%20Tennis%20(U)%20.nes" },
    JoeMacCavemanNinja: { name: "Joe & Mac - Caveman Ninja", url: "https://github.com/dientu4nut/NES/blob/master/Joe%20%26%20Mac%20-%20Caveman%20Ninja%20(U)%20.nes" },
    JohnElwaysQuarterback: { name: "John Elway s Quarterback", url: "https://github.com/dientu4nut/NES/blob/master/John%20Elway%20s%20Quarterback%20(U)%20.nes" },
    JordanVsBirdOneOnOne: { name: "Jordan Vs Bird - One On One", url: "https://github.com/dientu4nut/NES/blob/master/Jordan%20Vs%20Bird%20-%20One%20On%20One%20(U)%20.nes" },
    JourneytoSilius: { name: "Journey to Silius", url: "https://github.com/dientu4nut/NES/blob/master/Journey%20to%20Silius%20(U)%20.nes" },
    Joust: { name: "Joust", url: "https://github.com/dientu4nut/NES/blob/master/Joust%20(U)%20.nes" },
    JungleBookThe: { name: "Jungle Book The", url: "https://github.com/dientu4nut/NES/blob/master/Jungle%20Book%20The%20(U)%20.nes" },
    JurassicPark: { name: "Jurassic Park", url: "https://github.com/dientu4nut/NES/blob/master/Jurassic%20Park%20(U)%20.nes" },
    KabukiQuantumFighter: { name: "Kabuki - Quantum Fighter", url: "https://github.com/dientu4nut/NES/blob/master/Kabuki%20-%20Quantum%20Fighter%20(U)%20.nes" },
    KarateChamp: { name: "Karate Champ", url: "https://github.com/dientu4nut/NES/blob/master/Karate%20Champ%20(U)%20.nes" },
    KarateKidThe: { name: "Karate Kid The", url: "https://github.com/dientu4nut/NES/blob/master/Karate%20Kid%20The%20(U)%20.nes" },
    Karnov: { name: "Karnov", url: "https://github.com/dientu4nut/NES/blob/master/Karnov%20(U)%20.nes" },
    KickMaster: { name: "Kick Master", url: "https://github.com/dientu4nut/NES/blob/master/Kick%20Master%20(U)%20.nes" },
    KickOff: { name: "Kick Off ", url: "https://github.com/dientu4nut/NES/blob/master/Kick%20Off%20(E)%20.nes" },
    KickleCubicle: { name: "Kickle Cubicle", url: "https://github.com/dientu4nut/NES/blob/master/Kickle%20Cubicle%20(U)%20.nes" },
    KidKlown: { name: "Kid Klown", url: "https://github.com/dientu4nut/NES/blob/master/Kid%20Klown%20(U)%20.nes" },
    KidKoolandtheQuestforthe7WonderHerbs: { name: "Kid Kool and the Quest for the 7 Wonder Herbs", url: "https://github.com/dientu4nut/NES/blob/master/Kid%20Kool%20and%20the%20Quest%20for%20the%207%20Wonder%20Herbs%20(U)%20.nes" },
    KingsKnight: { name: "King s Knight", url: "https://github.com/dientu4nut/NES/blob/master/King%20s%20Knight%20(U)%20.nes" },
    KingsQuestV: { name: "King s Quest V", url: "https://github.com/dientu4nut/NES/blob/master/King%20s%20Quest%20V%20(U)%20.nes" },
    KingsoftheBeach: { name: "Kings of the Beach", url: "https://github.com/dientu4nut/NES/blob/master/Kings%20of%20the%20Beach%20(U)%20.nes" },
    KiwiKrazeABirdBrainedAdventure: { name: "Kiwi Kraze - A Bird-Brained Adventure ", url: "https://github.com/dientu4nut/NES/blob/master/Kiwi%20Kraze%20-%20A%20Bird-Brained%20Adventure%20%20(U)%20.nes" },
    KlashBall: { name: "Klash Ball", url: "https://github.com/dientu4nut/NES/blob/master/Klash%20Ball%20(U)%20.nes" },
    KnightRider: { name: "Knight Rider", url: "https://github.com/dientu4nut/NES/blob/master/Knight%20Rider%20(U)%20.nes" },
    KonamiHyperSoccer: { name: "Konami Hyper Soccer ", url: "https://github.com/dientu4nut/NES/blob/master/Konami%20Hyper%20Soccer%20(E)%20.nes" },
    KrionConquestThe: { name: "Krion Conquest The", url: "https://github.com/dientu4nut/NES/blob/master/Krion%20Conquest%20The%20(U)%20.nes" },
    KrustysFunHouse: { name: "Krusty s Fun House", url: "https://github.com/dientu4nut/NES/blob/master/Krusty%20s%20Fun%20House%20(U)%20.nes" },
    KungFu: { name: "Kung Fu", url: "https://github.com/dientu4nut/NES/blob/master/Kung%20Fu%20(U)%20.nes" },
    KungFuHeroes: { name: "Kung-Fu Heroes", url: "https://github.com/dientu4nut/NES/blob/master/Kung-Fu%20Heroes%20(U)%20.nes" },
    LEmpereur: { name: "L Empereur", url: "https://github.com/dientu4nut/NES/blob/master/L%20Empereur%20(U)%20.nes" },
    LaserInvasion: { name: "Laser Invasion", url: "https://github.com/dientu4nut/NES/blob/master/Laser%20Invasion%20(U)%20.nes" },
    LastActionHero: { name: "Last Action Hero", url: "https://github.com/dientu4nut/NES/blob/master/Last%20Action%20Hero%20(U)%20.nes" },
    LastNinjaThe: { name: "Last Ninja The", url: "https://github.com/dientu4nut/NES/blob/master/Last%20Ninja%20The%20(U)%20.nes" },
    LastStarfighterThe: { name: "Last Starfighter The", url: "https://github.com/dientu4nut/NES/blob/master/Last%20Starfighter%20The%20(U)%20.nes" },
    LeeTrevinosFightingGolf: { name: "Lee Trevino s Fighting Golf", url: "https://github.com/dientu4nut/NES/blob/master/Lee%20Trevino%20s%20Fighting%20Golf%20(U)%20.nes" },
    LegacyoftheWizard: { name: "Legacy of the Wizard", url: "https://github.com/dientu4nut/NES/blob/master/Legacy%20of%20the%20Wizard%20(U)%20.nes" },
    LegendofKageThe: { name: "Legend of Kage The", url: "https://github.com/dientu4nut/NES/blob/master/Legend%20of%20Kage%20The%20(U)%20.nes" },
    LegendofPrinceValiantThe: { name: "Legend of Prince Valiant The ", url: "https://github.com/dientu4nut/NES/blob/master/Legend%20of%20Prince%20Valiant%20The%20(E)%20.nes" },
    LegendofZeldaTheGC: { name: "Legend of Zelda, The (GC)", url: "https://github.com/dientu4nut/NES/blob/master/Legend%20of%20Zelda%2C%20The%20(GC).nes" },
    LegendoftheGhostLion: { name: "Legend of the Ghost Lion", url: "https://github.com/dientu4nut/NES/blob/master/Legend%20of%20the%20Ghost%20Lion%20(U)%20.nes" },
    LegendaryWings: { name: "Legendary Wings", url: "https://github.com/dientu4nut/NES/blob/master/Legendary%20Wings%20(U)%20.nes" },
    LegendsoftheDiamondTheBaseballChampionshipGame: { name: "Legends of the Diamond - The Baseball Championship Game", url: "https://github.com/dientu4nut/NES/blob/master/Legends%20of%20the%20Diamond%20-%20The%20Baseball%20Championship%20Game%20(U)%20.nes" },
    Lemmings: { name: "Lemmings", url: "https://github.com/dientu4nut/NES/blob/master/Lemmings%20(U)%20.nes" },
    LethalWeapon: { name: "Lethal Weapon", url: "https://github.com/dientu4nut/NES/blob/master/Lethal%20Weapon%20(U)%20.nes" },
    LifeForce: { name: "Life Force", url: "https://github.com/dientu4nut/NES/blob/master/Life%20Force%20(U)%20.nes" },
    LionKingThe: { name: "Lion King The ", url: "https://github.com/dientu4nut/NES/blob/master/Lion%20King%20The%20(E)%20.nes" },
    LittleLeagueBaseballChampionshipSeries: { name: "Little League Baseball - Championship Series", url: "https://github.com/dientu4nut/NES/blob/master/Little%20League%20Baseball%20-%20Championship%20Series%20(U)%20.nes" },
    LittleMermaidThe: { name: "Little Mermaid The", url: "https://github.com/dientu4nut/NES/blob/master/Little%20Mermaid%20The%20(U)%20.nes" },
    LittleNemoTheDreamMaster: { name: "Little Nemo - The Dream Master", url: "https://github.com/dientu4nut/NES/blob/master/Little%20Nemo%20-%20The%20Dream%20Master%20(U)%20.nes" },
    LittleNinjaBrothers: { name: "Little Ninja Brothers", url: "https://github.com/dientu4nut/NES/blob/master/Little%20Ninja%20Brothers%20(U)%20.nes" },
    LittleSamson: { name: "Little Samson", url: "https://github.com/dientu4nut/NES/blob/master/Little%20Samson%20(U)%20.nes" },
    LodeRunner: { name: "Lode Runner", url: "https://github.com/dientu4nut/NES/blob/master/Lode%20Runner%20(U)%20.nes" },
    LoneRangerThe: { name: "Lone Ranger The", url: "https://github.com/dientu4nut/NES/blob/master/Lone%20Ranger%20The%20(U)%20.nes" },
    Loopz: { name: "Loopz", url: "https://github.com/dientu4nut/NES/blob/master/Loopz%20(U)%20.nes" },
    LowGManTheLowGravityMan: { name: "Low G Man - The Low Gravity Man", url: "https://github.com/dientu4nut/NES/blob/master/Low%20G%20Man%20-%20The%20Low%20Gravity%20Man%20(U)%20.nes" },
    LunarPool: { name: "Lunar Pool", url: "https://github.com/dientu4nut/NES/blob/master/Lunar%20Pool%20(U)%20.nes" },
    MCKids: { name: "M.C Kids", url: "https://github.com/dientu4nut/NES/blob/master/M.C%20Kids%20(U)%20.nes" },
    MULE: { name: "M.U.L.E.", url: "https://github.com/dientu4nut/NES/blob/master/M.U.L.E.%20(U)%20.nes" },
    MUSCLE: { name: "M.U.S.C.L.E.", url: "https://github.com/dientu4nut/NES/blob/master/M.U.S.C.L.E.%20(U)%20.nes" },
    MadMax: { name: "Mad Max", url: "https://github.com/dientu4nut/NES/blob/master/Mad%20Max%20(U)%20.nes" },
    MafatConspiracyGolgo13: { name: "Mafat Conspiracy - Golgo 13", url: "https://github.com/dientu4nut/NES/blob/master/Mafat%20Conspiracy%20-%20Golgo%2013%20(U)%20.nes" },
    MagicDarts: { name: "Magic Darts", url: "https://github.com/dientu4nut/NES/blob/master/Magic%20Darts%20(U)%20.nes" },
    MagicJohnsonsFastBreak: { name: "Magic Johnson s Fast Break", url: "https://github.com/dientu4nut/NES/blob/master/Magic%20Johnson%20s%20Fast%20Break%20(U)%20.nes" },
    MagicofScheherazadeThe: { name: "Magic of Scheherazade The", url: "https://github.com/dientu4nut/NES/blob/master/Magic%20of%20Scheherazade%20The%20(U)%20.nes" },
    Magician: { name: "Magician", url: "https://github.com/dientu4nut/NES/blob/master/Magician%20(U)%20.nes" },
    Magmax: { name: "Magmax", url: "https://github.com/dientu4nut/NES/blob/master/Magmax%20(U)%20.nes" },
    ManiacMansion: { name: "Maniac Mansion", url: "https://github.com/dientu4nut/NES/blob/master/Maniac%20Mansion%20(U)%20.nes" },
    MappyLand: { name: "Mappy-Land", url: "https://github.com/dientu4nut/NES/blob/master/Mappy-Land%20(U)%20.nes" },
    MarbleMadness: { name: "Marble Madness", url: "https://github.com/dientu4nut/NES/blob/master/Marble%20Madness%20(U)%20.nes" },
    MarioYoshi: { name: "Mario & Yoshi [!]", url: "https://github.com/dientu4nut/NES/blob/master/Mario%20%26%20Yoshi%20(E)%20%5B!%5D.nes" },
    MarioBros: { name: "Mario Bros. [!]", url: "https://github.com/dientu4nut/NES/blob/master/Mario%20Bros.%20(E)%20%5B!%5D.nes" },
    MarioBrosClassic: { name: "Mario Bros. Classic [!]", url: "https://github.com/dientu4nut/NES/blob/master/Mario%20Bros.%20Classic%20(E)%20%5B!%5D.nes" },
    MarioisMissing: { name: "Mario is Missing ", url: "https://github.com/dientu4nut/NES/blob/master/Mario%20is%20Missing%20%20(U)%20.nes" },
    MariosTimeMachine: { name: "Mario s Time Machine ", url: "https://github.com/dientu4nut/NES/blob/master/Mario%20s%20Time%20Machine%20%20(U)%20.nes" },
    MechanizedAttack: { name: "Mechanized Attack", url: "https://github.com/dientu4nut/NES/blob/master/Mechanized%20Attack%20(U)%20.nes" },
    Megaman: { name: "Megaman", url: "https://github.com/dientu4nut/NES/blob/master/Megaman%20(U)%20.nes" },
    MegamanII: { name: "Megaman II", url: "https://github.com/dientu4nut/NES/blob/master/Megaman%20II%20(U)%20.nes" },
    MegamanIII: { name: "Megaman III", url: "https://github.com/dientu4nut/NES/blob/master/Megaman%20III%20(U)%20.nes" },
    MegamanV: { name: "Megaman V", url: "https://github.com/dientu4nut/NES/blob/master/Megaman%20V%20(U)%20.nes" },
    MegamanVI: { name: "Megaman VI", url: "https://github.com/dientu4nut/NES/blob/master/Megaman%20VI%20(U)%20.nes" },
    MendelPalace: { name: "Mendel Palace", url: "https://github.com/dientu4nut/NES/blob/master/Mendel%20Palace%20(U)%20.nes" },
    MetalGear: { name: "Metal Gear", url: "https://github.com/dientu4nut/NES/blob/master/Metal%20Gear%20(U)%20.nes" },
    MetalMechManMachine: { name: "Metal Mech - Man & Machine", url: "https://github.com/dientu4nut/NES/blob/master/Metal%20Mech%20-%20Man%20%26%20Machine%20(U)%20.nes" },
    MetalStorm: { name: "Metal Storm", url: "https://github.com/dientu4nut/NES/blob/master/Metal%20Storm%20(U)%20.nes" },
    MichaelAndrettisWorldGrandPrix: { name: "Michael Andretti s World Grand Prix", url: "https://github.com/dientu4nut/NES/blob/master/Michael%20Andretti%20s%20World%20Grand%20Prix%20(U)%20.nes" },
    MickeyMousecapade: { name: "Mickey Mousecapade", url: "https://github.com/dientu4nut/NES/blob/master/Mickey%20Mousecapade%20(U)%20.nes" },
    MickeysAdventuresinNumberland: { name: "Mickey s Adventures in Numberland", url: "https://github.com/dientu4nut/NES/blob/master/Mickey%20s%20Adventures%20in%20Numberland%20(U)%20.nes" },
    MickeysSafariinLetterland: { name: "Mickey s Safari in Letterland", url: "https://github.com/dientu4nut/NES/blob/master/Mickey%20s%20Safari%20in%20Letterland%20(U)%20.nes" },
    MightandMagic: { name: "Might and Magic", url: "https://github.com/dientu4nut/NES/blob/master/Might%20and%20Magic%20(U)%20.nes" },
    MightyBombJack: { name: "Mighty Bomb Jack", url: "https://github.com/dientu4nut/NES/blob/master/Mighty%20Bomb%20Jack%20(U)%20.nes" },
    MightyFinalFight: { name: "Mighty Final Fight", url: "https://github.com/dientu4nut/NES/blob/master/Mighty%20Final%20Fight%20(U)%20.nes" },
    Millipede: { name: "Millipede", url: "https://github.com/dientu4nut/NES/blob/master/Millipede%20(U)%20.nes" },
    MilonsSecretCastle: { name: "Milon s Secret Castle", url: "https://github.com/dientu4nut/NES/blob/master/Milon%20s%20Secret%20Castle%20(U)%20.nes" },
    MiraclePianoTeachingSystemThe: { name: "Miracle Piano Teaching System The", url: "https://github.com/dientu4nut/NES/blob/master/Miracle%20Piano%20Teaching%20System%20The%20(U)%20.nes" },
    MissionImpossible: { name: "Mission - Impossible", url: "https://github.com/dientu4nut/NES/blob/master/Mission%20-%20Impossible%20(U)%20.nes" },
    Monopoly: { name: "Monopoly", url: "https://github.com/dientu4nut/NES/blob/master/Monopoly%20(U)%20.nes" },
    MonsterInMyPocket: { name: "Monster In My Pocket", url: "https://github.com/dientu4nut/NES/blob/master/Monster%20In%20My%20Pocket%20(U)%20.nes" },
    MonsterParty: { name: "Monster Party", url: "https://github.com/dientu4nut/NES/blob/master/Monster%20Party%20(U)%20.nes" },
    MonsterTruckRally: { name: "Monster Truck Rally", url: "https://github.com/dientu4nut/NES/blob/master/Monster%20Truck%20Rally%20(U)%20.nes" },
    MotorCityPatrol: { name: "Motor City Patrol", url: "https://github.com/dientu4nut/NES/blob/master/Motor%20City%20Patrol%20(U)%20.nes" },
    MrGimmick: { name: "Mr. Gimmick ", url: "https://github.com/dientu4nut/NES/blob/master/Mr.%20Gimmick%20(E)%20.nes" },
    MsPacMan: { name: "Ms. Pac-Man", url: "https://github.com/dientu4nut/NES/blob/master/Ms.%20Pac-Man%20(U)%20.nes" },
    MutantVirusThe: { name: "Mutant Virus The", url: "https://github.com/dientu4nut/NES/blob/master/Mutant%20Virus%20The%20(U)%20.nes" },
    MysteryQuest: { name: "Mystery Quest", url: "https://github.com/dientu4nut/NES/blob/master/Mystery%20Quest%20(U)%20.nes" },
    NARC: { name: "NARC", url: "https://github.com/dientu4nut/NES/blob/master/NARC%20(U)%20.nes" },
    NESOpenTournamentGolf: { name: "NES Open Tournament Golf", url: "https://github.com/dientu4nut/NES/blob/master/NES%20Open%20Tournament%20Golf%20(U)%20.nes" },
    NESPlayActionFootball: { name: "NES Play Action Football", url: "https://github.com/dientu4nut/NES/blob/master/NES%20Play%20Action%20Football%20(U)%20.nes" },
    NFLFootball: { name: "NFL Football", url: "https://github.com/dientu4nut/NES/blob/master/NFL%20Football%20(U)%20.nes" },
    NTF2SystemCartU: { name: "NTF2 System Cart (U)", url: "https://github.com/dientu4nut/NES/blob/master/NTF2%20System%20Cart%20(U).nes" },
    NewGhostbustersII: { name: "New Ghostbusters II ", url: "https://github.com/dientu4nut/NES/blob/master/New%20Ghostbusters%20II%20(E)%20.nes" },
    NigelMansellsWorldChampionshipChallenge: { name: "Nigel Mansell s World Championship Challenge", url: "https://github.com/dientu4nut/NES/blob/master/Nigel%20Mansell%20s%20World%20Championship%20Challenge%20(U)%20.nes" },
    NightmareonElmStreetA: { name: "Nightmare on Elm Street A", url: "https://github.com/dientu4nut/NES/blob/master/Nightmare%20on%20Elm%20Street%20A%20(U)%20.nes" },
    Nightshade: { name: "Nightshade", url: "https://github.com/dientu4nut/NES/blob/master/Nightshade%20(U)%20.nes" },
    NinjaCrusaders: { name: "Ninja Crusaders", url: "https://github.com/dientu4nut/NES/blob/master/Ninja%20Crusaders%20(U)%20.nes" },
    NinjaGaiden: { name: "Ninja Gaiden", url: "https://github.com/dientu4nut/NES/blob/master/Ninja%20Gaiden%20(U)%20.nes" },
    NinjaGaidenIITheDarkSwordofChaos: { name: "Ninja Gaiden II - The Dark Sword of Chaos", url: "https://github.com/dientu4nut/NES/blob/master/Ninja%20Gaiden%20II%20-%20The%20Dark%20Sword%20of%20Chaos%20(U)%20.nes" },
    NinjaGaidenIIITheAncientShipofDoom: { name: "Ninja Gaiden III - The Ancient Ship of Doom", url: "https://github.com/dientu4nut/NES/blob/master/Ninja%20Gaiden%20III%20-%20The%20Ancient%20Ship%20of%20Doom%20(U)%20.nes" },
    NinjaKid: { name: "Ninja Kid", url: "https://github.com/dientu4nut/NES/blob/master/Ninja%20Kid%20(U)%20.nes" },
    NintendoWorldChampionships1990: { name: "Nintendo World Championships 1990", url: "https://github.com/dientu4nut/NES/blob/master/Nintendo%20World%20Championships%201990%20(U)%20.nes" },
    NintendoWorldCup: { name: "Nintendo World Cup", url: "https://github.com/dientu4nut/NES/blob/master/Nintendo%20World%20Cup%20(U)%20.nes" },
    NoahsArk: { name: "Noah s Ark ", url: "https://github.com/dientu4nut/NES/blob/master/Noah%20s%20Ark%20(E)%20.nes" },
    NobunagasAmbition: { name: "Nobunaga s Ambition", url: "https://github.com/dientu4nut/NES/blob/master/Nobunaga%20s%20Ambition%20(U)%20.nes" },
    NobunagasAmbition2: { name: "Nobunaga s Ambition 2", url: "https://github.com/dientu4nut/NES/blob/master/Nobunaga%20s%20Ambition%202%20(U)%20.nes" },
    NorthSouth: { name: "North & South", url: "https://github.com/dientu4nut/NES/blob/master/North%20%26%20South%20(U)%20.nes" },
    OperationWolf: { name: "Operation Wolf", url: "https://github.com/dientu4nut/NES/blob/master/Operation%20Wolf%20(U)%20.nes" },
    Orb3D: { name: "Orb 3D", url: "https://github.com/dientu4nut/NES/blob/master/Orb%203D%20(U)%20.nes" },
    Othello: { name: "Othello", url: "https://github.com/dientu4nut/NES/blob/master/Othello%20(U)%20.nes" },
    OverHorizon: { name: "Over Horizon ", url: "https://github.com/dientu4nut/NES/blob/master/Over%20Horizon%20(E)%20.nes" },
    Overlord: { name: "Overlord", url: "https://github.com/dientu4nut/NES/blob/master/Overlord%20(U)%20.nes" },
    POWPrisonersofWar: { name: "P.O.W. - Prisoners of War", url: "https://github.com/dientu4nut/NES/blob/master/P.O.W.%20-%20Prisoners%20of%20War%20(U)%20.nes" },
    PacManNamco: { name: "Pac-Man(Namco) ", url: "https://github.com/dientu4nut/NES/blob/master/Pac-Man%20(U)%20(Namco)%20.nes" },
    PacManTengen: { name: "Pac-Man(Tengen) ", url: "https://github.com/dientu4nut/NES/blob/master/Pac-Man%20(U)%20(Tengen)%20.nes" },
    Palamedes: { name: "Palamedes", url: "https://github.com/dientu4nut/NES/blob/master/Palamedes%20(U)%20.nes" },
    PanicRestaurant: { name: "Panic Restaurant", url: "https://github.com/dientu4nut/NES/blob/master/Panic%20Restaurant%20(U)%20.nes" },
    Paperboy: { name: "Paperboy", url: "https://github.com/dientu4nut/NES/blob/master/Paperboy%20(U)%20.nes" },
    Paperboy2: { name: "Paperboy 2", url: "https://github.com/dientu4nut/NES/blob/master/Paperboy%202%20(U)%20.nes" },
    ParasolStarsTheStoryofBubbleBobble3: { name: "Parasol Stars - The Story of Bubble Bobble 3 ", url: "https://github.com/dientu4nut/NES/blob/master/Parasol%20Stars%20-%20The%20Story%20of%20Bubble%20Bobble%203%20(E)%20.nes" },
    Parodius: { name: "Parodius ", url: "https://github.com/dientu4nut/NES/blob/master/Parodius%20(E)%20.nes" },
    PerfectFit: { name: "Perfect Fit", url: "https://github.com/dientu4nut/NES/blob/master/Perfect%20Fit%20(U)%20.nes" },
    PeterPanThePirates: { name: "Peter Pan & The Pirates", url: "https://github.com/dientu4nut/NES/blob/master/Peter%20Pan%20%26%20The%20Pirates%20(U)%20.nes" },
    PhantomFighter: { name: "Phantom Fighter", url: "https://github.com/dientu4nut/NES/blob/master/Phantom%20Fighter%20(U)%20.nes" },
    Pictionary: { name: "Pictionary", url: "https://github.com/dientu4nut/NES/blob/master/Pictionary%20(U)%20.nes" },
    PinBot: { name: "Pin Bot", url: "https://github.com/dientu4nut/NES/blob/master/Pin%20Bot%20(U)%20.nes" },
    PinballQuest: { name: "Pinball Quest", url: "https://github.com/dientu4nut/NES/blob/master/Pinball%20Quest%20(U)%20.nes" },
    PipeDream: { name: "Pipe Dream", url: "https://github.com/dientu4nut/NES/blob/master/Pipe%20Dream%20(U)%20.nes" },
    Pirates: { name: "Pirates ", url: "https://github.com/dientu4nut/NES/blob/master/Pirates%20%20(U)%20.nes" },
    PowerBlade: { name: "Power Blade", url: "https://github.com/dientu4nut/NES/blob/master/Power%20Blade%20(U)%20.nes" },
    PowerBlade2: { name: "Power Blade 2", url: "https://github.com/dientu4nut/NES/blob/master/Power%20Blade%202%20(U)%20.nes" },
    PowerPunch2: { name: "Power Punch 2", url: "https://github.com/dientu4nut/NES/blob/master/Power%20Punch%202%20(U)%20.nes" },
    Predator: { name: "Predator", url: "https://github.com/dientu4nut/NES/blob/master/Predator%20(U)%20.nes" },
    PrinceofPersia: { name: "Prince of Persia", url: "https://github.com/dientu4nut/NES/blob/master/Prince%20of%20Persia%20(U)%20.nes" },
    PrincessTomatoinSaladKingdom: { name: "Princess Tomato in Salad Kingdom", url: "https://github.com/dientu4nut/NES/blob/master/Princess%20Tomato%20in%20Salad%20Kingdom%20(U)%20.nes" },
    ProSportHockey: { name: "Pro Sport Hockey", url: "https://github.com/dientu4nut/NES/blob/master/Pro%20Sport%20Hockey%20(U)%20.nes" },
    PunchOut: { name: "Punch-Out  ", url: "https://github.com/dientu4nut/NES/blob/master/Punch-Out%20%20%20(U)%20.nes" },
    PunisherThe: { name: "Punisher The", url: "https://github.com/dientu4nut/NES/blob/master/Punisher%20The%20(U)%20.nes" },
    PussnBootsPerosGreatAdventure: { name: "Puss  n Boots - Pero s Great Adventure", url: "https://github.com/dientu4nut/NES/blob/master/Puss%20%20n%20Boots%20-%20Pero%20s%20Great%20Adventure%20(U)%20.nes" },
    Puzznic: { name: "Puzznic", url: "https://github.com/dientu4nut/NES/blob/master/Puzznic%20(U)%20.nes" },
    Qbert: { name: "Q-bert", url: "https://github.com/dientu4nut/NES/blob/master/Q-bert%20(U)%20.nes" },
    Qix: { name: "Qix", url: "https://github.com/dientu4nut/NES/blob/master/Qix%20(U)%20.nes" },
    RBIBaseball: { name: "R.B.I. Baseball", url: "https://github.com/dientu4nut/NES/blob/master/R.B.I.%20Baseball%20(U)%20.nes" },
    RCProAmII: { name: "R.C. Pro-Am II", url: "https://github.com/dientu4nut/NES/blob/master/R.C.%20Pro-Am%20II%20(U)%20.nes" },
    READMEmd: { name: "README.md", url: "https://github.com/dientu4nut/NES/blob/master/README.md" },
    RaceAmerica: { name: "Race America", url: "https://github.com/dientu4nut/NES/blob/master/Race%20America%20(U)%20.nes" },
    RacermateChallengerIIV602002U: { name: "Racermate Challenger II V6.02.002 (U)", url: "https://github.com/dientu4nut/NES/blob/master/Racermate%20Challenger%20II%20V6.02.002%20(U).nes" },
    RacketAttack: { name: "Racket Attack", url: "https://github.com/dientu4nut/NES/blob/master/Racket%20Attack%20(U)%20.nes" },
    RacketsRivals: { name: "Rackets & Rivals ", url: "https://github.com/dientu4nut/NES/blob/master/Rackets%20%26%20Rivals%20(E)%20.nes" },
    RadRacer: { name: "Rad Racer", url: "https://github.com/dientu4nut/NES/blob/master/Rad%20Racer%20(U)%20.nes" },
    RadRacer2: { name: "Rad Racer 2", url: "https://github.com/dientu4nut/NES/blob/master/Rad%20Racer%202%20(U)%20.nes" },
    RaidonBungelingBay: { name: "Raid on Bungeling Bay", url: "https://github.com/dientu4nut/NES/blob/master/Raid%20on%20Bungeling%20Bay%20(U)%20.nes" },
    RainbowIslandsTheStoryofBubbleBobble2: { name: "Rainbow Islands - The Story of Bubble Bobble 2", url: "https://github.com/dientu4nut/NES/blob/master/Rainbow%20Islands%20-%20The%20Story%20of%20Bubble%20Bobble%202%20(U)%20.nes" },
    RallyBike: { name: "Rally Bike", url: "https://github.com/dientu4nut/NES/blob/master/Rally%20Bike%20(U)%20.nes" },
    Rampage: { name: "Rampage", url: "https://github.com/dientu4nut/NES/blob/master/Rampage%20(U)%20.nes" },
    Rampart: { name: "Rampart", url: "https://github.com/dientu4nut/NES/blob/master/Rampart%20(U)%20.nes" },
    RemoteControl: { name: "Remote Control", url: "https://github.com/dientu4nut/NES/blob/master/Remote%20Control%20(U)%20.nes" },
    RenStimpyShowThe: { name: "Ren & Stimpy Show The", url: "https://github.com/dientu4nut/NES/blob/master/Ren%20%26%20Stimpy%20Show%20The%20(U)%20.nes" },
    Renegade: { name: "Renegade", url: "https://github.com/dientu4nut/NES/blob/master/Renegade%20(U)%20.nes" },
    RescueTheEmbassyMission: { name: "Rescue - The Embassy Mission", url: "https://github.com/dientu4nut/NES/blob/master/Rescue%20-%20The%20Embassy%20Mission%20(U)%20.nes" },
    RingKing: { name: "Ring King", url: "https://github.com/dientu4nut/NES/blob/master/Ring%20King%20(U)%20.nes" },
    RiverCityRansom: { name: "River City Ransom", url: "https://github.com/dientu4nut/NES/blob/master/River%20City%20Ransom%20(U)%20.nes" },
    RoadFighter: { name: "Road Fighter ", url: "https://github.com/dientu4nut/NES/blob/master/Road%20Fighter%20(E)%20.nes" },
    RoadBlasters: { name: "RoadBlasters", url: "https://github.com/dientu4nut/NES/blob/master/RoadBlasters%20(U)%20.nes" },
    RoboWarrior: { name: "Robo Warrior", url: "https://github.com/dientu4nut/NES/blob/master/Robo%20Warrior%20(U)%20.nes" },
    RoboCop: { name: "RoboCop", url: "https://github.com/dientu4nut/NES/blob/master/RoboCop%20(U)%20.nes" },
    RoboCop3: { name: "RoboCop 3", url: "https://github.com/dientu4nut/NES/blob/master/RoboCop%203%20(U)%20.nes" },
    RocknBall: { name: "Rock  n  Ball", url: "https://github.com/dientu4nut/NES/blob/master/Rock%20%20n%20%20Ball%20(U)%20.nes" },
    RocketRanger: { name: "Rocket Ranger", url: "https://github.com/dientu4nut/NES/blob/master/Rocket%20Ranger%20(U)%20.nes" },
    RocketeerThe: { name: "Rocketeer The", url: "https://github.com/dientu4nut/NES/blob/master/Rocketeer%20The%20(U)%20.nes" },
    RockinKats: { name: "Rockin  Kats", url: "https://github.com/dientu4nut/NES/blob/master/Rockin%20%20Kats%20(U)%20.nes" },
    RodLand: { name: "Rod Land ", url: "https://github.com/dientu4nut/NES/blob/master/Rod%20Land%20(E)%20.nes" },
    RogerClemensMVPBaseball: { name: "Roger Clemens  MVP Baseball", url: "https://github.com/dientu4nut/NES/blob/master/Roger%20Clemens%20%20MVP%20Baseball%20(U)%20.nes" },
    Rollerball: { name: "Rollerball", url: "https://github.com/dientu4nut/NES/blob/master/Rollerball%20(U)%20.nes" },
    RollerbladeRacer: { name: "Rollerblade Racer", url: "https://github.com/dientu4nut/NES/blob/master/Rollerblade%20Racer%20(U)%20.nes" },
    Rollergames: { name: "Rollergames", url: "https://github.com/dientu4nut/NES/blob/master/Rollergames%20(U)%20.nes" },
    RomanceofTheThreeKingdoms: { name: "Romance of The Three Kingdoms", url: "https://github.com/dientu4nut/NES/blob/master/Romance%20of%20The%20Three%20Kingdoms%20(U)%20.nes" },
    RomanceofTheThreeKingdomsII: { name: "Romance of The Three Kingdoms II", url: "https://github.com/dientu4nut/NES/blob/master/Romance%20of%20The%20Three%20Kingdoms%20II%20(U)%20.nes" },
    Roundball2on2Challenge: { name: "Roundball - 2-on-2 Challenge", url: "https://github.com/dientu4nut/NES/blob/master/Roundball%20-%202-on-2%20Challenge%20(U)%20.nes" },
    SamuraiSpiritsRexSoftFullversionU: { name: "Samurai Spirits (Rex Soft) (Full version) [U]", url: "https://github.com/dientu4nut/NES/blob/master/Samurai%20Spirits%20(Rex%20Soft)%20(Full%20version)%20%5BU%5D.nes" },
    ScarabeusSample: { name: "Scarabeus(Sample)", url: "https://github.com/dientu4nut/NES/blob/master/Scarabeus%20(U)%20(Sample).nes" },
    SectionZ: { name: "Section Z", url: "https://github.com/dientu4nut/NES/blob/master/Section%20Z%20(U)%20.nes" },
    Seicross: { name: "Seicross", url: "https://github.com/dientu4nut/NES/blob/master/Seicross%20(U)%20.nes" },
    SesameStreet123: { name: "Sesame Street 123", url: "https://github.com/dientu4nut/NES/blob/master/Sesame%20Street%20123%20(U)%20.nes" },
    SesameStreet123ABC: { name: "Sesame Street 123 - ABC", url: "https://github.com/dientu4nut/NES/blob/master/Sesame%20Street%20123%20-%20ABC%20(U)%20.nes" },
    SesameStreetABC: { name: "Sesame Street ABC", url: "https://github.com/dientu4nut/NES/blob/master/Sesame%20Street%20ABC%20(U)%20.nes" },
    SesameStreetCountdown: { name: "Sesame Street Countdown", url: "https://github.com/dientu4nut/NES/blob/master/Sesame%20Street%20Countdown%20(U)%20.nes" },
    ShadowoftheNinja: { name: "Shadow of the Ninja", url: "https://github.com/dientu4nut/NES/blob/master/Shadow%20of%20the%20Ninja%20(U)%20.nes" },
    Shadowgate: { name: "Shadowgate", url: "https://github.com/dientu4nut/NES/blob/master/Shadowgate%20(U)%20.nes" },
    Shatterhand: { name: "Shatterhand", url: "https://github.com/dientu4nut/NES/blob/master/Shatterhand%20(U)%20.nes" },
    ShingenTheRuler: { name: "Shingen The Ruler", url: "https://github.com/dientu4nut/NES/blob/master/Shingen%20The%20Ruler%20(U)%20.nes" },
    ShootingRange: { name: "Shooting Range", url: "https://github.com/dientu4nut/NES/blob/master/Shooting%20Range%20(U)%20.nes" },
    ShortOrderEggsplode: { name: "Short Order - Eggsplode", url: "https://github.com/dientu4nut/NES/blob/master/Short%20Order%20-%20Eggsplode%20(U)%20.nes" },
    SidePocket: { name: "Side Pocket", url: "https://github.com/dientu4nut/NES/blob/master/Side%20Pocket%20(U)%20.nes" },
    Silkworm: { name: "Silkworm", url: "https://github.com/dientu4nut/NES/blob/master/Silkworm%20(U)%20.nes" },
    SilverSurfer: { name: "Silver Surfer", url: "https://github.com/dientu4nut/NES/blob/master/Silver%20Surfer%20(U)%20.nes" },
    SimpsonsBartvstheSpaceMutants: { name: "Simpsons - Bart vs. the Space Mutants", url: "https://github.com/dientu4nut/NES/blob/master/Simpsons%20-%20Bart%20vs.%20the%20Space%20Mutants.nes" },
    SimpsonsTheBartVstheWorld: { name: "Simpsons The - Bart Vs. the World", url: "https://github.com/dientu4nut/NES/blob/master/Simpsons%20The%20-%20Bart%20Vs.%20the%20World%20(U)%20.nes" },
    SimpsonsTheBartmanMeetsRadioactiveMan: { name: "Simpsons The - Bartman Meets Radioactive Man", url: "https://github.com/dientu4nut/NES/blob/master/Simpsons%20The%20-%20Bartman%20Meets%20Radioactive%20Man%20(U)%20.nes" },
    SkateorDie: { name: "Skate or Die ", url: "https://github.com/dientu4nut/NES/blob/master/Skate%20or%20Die%20%20(U)%20.nes" },
    SkateorDie2TheSearchforDoubleTrouble: { name: "Skate or Die 2 - The Search for Double Trouble", url: "https://github.com/dientu4nut/NES/blob/master/Skate%20or%20Die%202%20-%20The%20Search%20for%20Double%20Trouble%20(U)%20.nes" },
    SkiorDie: { name: "Ski or Die", url: "https://github.com/dientu4nut/NES/blob/master/Ski%20or%20Die%20(U)%20.nes" },
    SkyKid: { name: "Sky Kid", url: "https://github.com/dientu4nut/NES/blob/master/Sky%20Kid%20(U)%20.nes" },
    SkyShark: { name: "Sky Shark", url: "https://github.com/dientu4nut/NES/blob/master/Sky%20Shark%20(U)%20.nes" },
    Slalom: { name: "Slalom", url: "https://github.com/dientu4nut/NES/blob/master/Slalom%20(U)%20.nes" },
    SmashTV: { name: "Smash T.V.", url: "https://github.com/dientu4nut/NES/blob/master/Smash%20T.V.%20(U)%20.nes" },
    SnakeRattleNRoll: { name: "Snake Rattle N Roll", url: "https://github.com/dientu4nut/NES/blob/master/Snake%20Rattle%20N%20Roll%20(U)%20.nes" },
    SnakesRevenge: { name: "Snake s Revenge", url: "https://github.com/dientu4nut/NES/blob/master/Snake%20s%20Revenge%20(U)%20.nes" },
    SnoopysSillySportsSpectacular: { name: "Snoopy s Silly Sports Spectacular", url: "https://github.com/dientu4nut/NES/blob/master/Snoopy%20s%20Silly%20Sports%20Spectacular%20(U)%20.nes" },
    SnowBrothers: { name: "Snow Brothers", url: "https://github.com/dientu4nut/NES/blob/master/Snow%20Brothers%20(U)%20.nes" },
    SolarJetmanHuntfortheGoldenWarpship: { name: "Solar Jetman - Hunt for the Golden Warpship", url: "https://github.com/dientu4nut/NES/blob/master/Solar%20Jetman%20-%20Hunt%20for%20the%20Golden%20Warpship%20(U)%20.nes" },
    SolomonsKey: { name: "Solomon s Key", url: "https://github.com/dientu4nut/NES/blob/master/Solomon%20s%20Key%20(U)%20.nes" },
    SolsticeTheQuestfortheStaffofDemnos: { name: "Solstice - The Quest for the Staff of Demnos", url: "https://github.com/dientu4nut/NES/blob/master/Solstice%20-%20The%20Quest%20for%20the%20Staff%20of%20Demnos%20(U)%20.nes" },
    SpaceShuttleProject: { name: "Space Shuttle Project", url: "https://github.com/dientu4nut/NES/blob/master/Space%20Shuttle%20Project%20(U)%20.nes" },
    Spelunker: { name: "Spelunker", url: "https://github.com/dientu4nut/NES/blob/master/Spelunker%20(U)%20.nes" },
    SpiderManReturnoftheSinisterSix: { name: "Spider-Man - Return of the Sinister Six", url: "https://github.com/dientu4nut/NES/blob/master/Spider-Man%20-%20Return%20of%20the%20Sinister%20Six%20(U)%20.nes" },
    Spot: { name: "Spot", url: "https://github.com/dientu4nut/NES/blob/master/Spot%20(U)%20.nes" },
    SpyHunter: { name: "Spy Hunter", url: "https://github.com/dientu4nut/NES/blob/master/Spy%20Hunter%20(U)%20.nes" },
    SpyVsSpy: { name: "Spy Vs Spy", url: "https://github.com/dientu4nut/NES/blob/master/Spy%20Vs%20Spy%20(U)%20.nes" },
    Sqoon: { name: "Sqoon", url: "https://github.com/dientu4nut/NES/blob/master/Sqoon%20(U)%20.nes" },
    StadiumEvents: { name: "Stadium Events", url: "https://github.com/dientu4nut/NES/blob/master/Stadium%20Events%20(U)%20.nes" },
    StanleyTheSearchforDrLivingston: { name: "Stanley - The Search for Dr. Livingston", url: "https://github.com/dientu4nut/NES/blob/master/Stanley%20-%20The%20Search%20for%20Dr.%20Livingston%20(U)%20.nes" },
    StarForce: { name: "Star Force", url: "https://github.com/dientu4nut/NES/blob/master/Star%20Force%20(U)%20.nes" },
    StarSoldier: { name: "Star Soldier", url: "https://github.com/dientu4nut/NES/blob/master/Star%20Soldier%20(U)%20.nes" },
    StarTrek25thAnniversary: { name: "Star Trek - 25th Anniversary", url: "https://github.com/dientu4nut/NES/blob/master/Star%20Trek%20-%2025th%20Anniversary%20(U)%20.nes" },
    StarTrekTheNextGeneration: { name: "Star Trek - The Next Generation", url: "https://github.com/dientu4nut/NES/blob/master/Star%20Trek%20-%20The%20Next%20Generation%20(U)%20.nes" },
    StarVoyager: { name: "Star Voyager", url: "https://github.com/dientu4nut/NES/blob/master/Star%20Voyager%20(U)%20.nes" },
    StarWars: { name: "Star Wars", url: "https://github.com/dientu4nut/NES/blob/master/Star%20Wars%20(U)%20.nes" },
    StarWarsTheEmpireStrikesBack: { name: "Star Wars - The Empire Strikes Back", url: "https://github.com/dientu4nut/NES/blob/master/Star%20Wars%20-%20The%20Empire%20Strikes%20Back%20(U)%20.nes" },
    StarshipHector: { name: "Starship Hector", url: "https://github.com/dientu4nut/NES/blob/master/Starship%20Hector%20(U)%20.nes" },
    Startropics: { name: "Startropics", url: "https://github.com/dientu4nut/NES/blob/master/Startropics%20(U)%20.nes" },
    StealthATF: { name: "Stealth ATF", url: "https://github.com/dientu4nut/NES/blob/master/Stealth%20ATF%20(U)%20.nes" },
    Stinger: { name: "Stinger", url: "https://github.com/dientu4nut/NES/blob/master/Stinger%20(U)%20.nes" },
    StreetCop: { name: "Street Cop", url: "https://github.com/dientu4nut/NES/blob/master/Street%20Cop%20(U)%20.nes" },
    StreetFighter2010TheFinalFight: { name: "Street Fighter 2010 - The Final Fight", url: "https://github.com/dientu4nut/NES/blob/master/Street%20Fighter%202010%20-%20The%20Final%20Fight%20(U)%20.nes" },
    Strider: { name: "Strider", url: "https://github.com/dientu4nut/NES/blob/master/Strider%20(U)%20.nes" },
    SummerCarnival92ReccaU: { name: "Summer Carnival  92 - Recca (U)", url: "https://github.com/dientu4nut/NES/blob/master/Summer%20Carnival%20%2092%20-%20Recca%20(U).nes" },
    SuperC: { name: "Super C", url: "https://github.com/dientu4nut/NES/blob/master/Super%20C%20(U)%20.nes" },
    SuperCars: { name: "Super Cars", url: "https://github.com/dientu4nut/NES/blob/master/Super%20Cars%20(U)%20.nes" },
    SuperDodgeBall: { name: "Super Dodge Ball", url: "https://github.com/dientu4nut/NES/blob/master/Super%20Dodge%20Ball%20(U)%20.nes" },
    SuperGloveBall: { name: "Super Glove Ball", url: "https://github.com/dientu4nut/NES/blob/master/Super%20Glove%20Ball%20(U)%20.nes" },
    SuperJeopardy: { name: "Super Jeopardy ", url: "https://github.com/dientu4nut/NES/blob/master/Super%20Jeopardy%20%20(U)%20.nes" },
    SuperMarioBrosDuckHunt: { name: "Super Mario Bros. + Duck Hunt", url: "https://github.com/dientu4nut/NES/blob/master/Super%20Mario%20Bros.%20%2B%20Duck%20Hunt%20(U)%20.nes" },
    SuperMarioBros2: { name: "Super Mario Bros. 2 [!]", url: "https://github.com/dientu4nut/NES/blob/master/Super%20Mario%20Bros.%202%20(E)%20%5B!%5D.nes" },
    SuperMarioBros3: { name: "Super Mario Bros. 3 [!]", url: "https://github.com/dientu4nut/NES/blob/master/Super%20Mario%20Bros.%203%20(E)%20%5B!%5D.nes" },
    SuperPitfall: { name: "Super Pitfall", url: "https://github.com/dientu4nut/NES/blob/master/Super%20Pitfall%20(U)%20.nes" },
    SuperSpikeVBall: { name: "Super Spike V Ball", url: "https://github.com/dientu4nut/NES/blob/master/Super%20Spike%20V%20Ball%20(U)%20.nes" },
    SuperSpikeVBallNintendoWorldCup: { name: "Super Spike V Ball + Nintendo World Cup", url: "https://github.com/dientu4nut/NES/blob/master/Super%20Spike%20V%20Ball%20%2B%20Nintendo%20World%20Cup%20(U)%20.nes" },
    SuperSpyHunter: { name: "Super Spy Hunter", url: "https://github.com/dientu4nut/NES/blob/master/Super%20Spy%20Hunter%20(U)%20.nes" },
    SuperTeamGames: { name: "Super Team Games", url: "https://github.com/dientu4nut/NES/blob/master/Super%20Team%20Games%20(U)%20.nes" },
    SuperTurrican: { name: "Super Turrican ", url: "https://github.com/dientu4nut/NES/blob/master/Super%20Turrican%20(E)%20.nes" },
    Superman: { name: "Superman", url: "https://github.com/dientu4nut/NES/blob/master/Superman%20(U)%20.nes" },
    SwampThing: { name: "Swamp Thing", url: "https://github.com/dientu4nut/NES/blob/master/Swamp%20Thing%20(U)%20.nes" },
    SwordMaster: { name: "Sword Master", url: "https://github.com/dientu4nut/NES/blob/master/Sword%20Master%20(U)%20.nes" },
    SwordsandSerpents: { name: "Swords and Serpents", url: "https://github.com/dientu4nut/NES/blob/master/Swords%20and%20Serpents%20(U)%20.nes" },
    TagTeamWrestling: { name: "Tag Team Wrestling", url: "https://github.com/dientu4nut/NES/blob/master/Tag%20Team%20Wrestling%20(U)%20.nes" },
    TaleSpin: { name: "TaleSpin", url: "https://github.com/dientu4nut/NES/blob/master/TaleSpin%20(U)%20.nes" },
    TargetRenegade: { name: "Target - Renegade", url: "https://github.com/dientu4nut/NES/blob/master/Target%20-%20Renegade%20(U)%20.nes" },
    TecmoBaseball: { name: "Tecmo Baseball", url: "https://github.com/dientu4nut/NES/blob/master/Tecmo%20Baseball%20(U)%20.nes" },
    TecmoCupSoccerGame: { name: "Tecmo Cup - Soccer Game", url: "https://github.com/dientu4nut/NES/blob/master/Tecmo%20Cup%20-%20Soccer%20Game%20(U)%20.nes" },
    TecmoSuperBowl: { name: "Tecmo Super Bowl", url: "https://github.com/dientu4nut/NES/blob/master/Tecmo%20Super%20Bowl%20(U)%20.nes" },
    TecmoWorldWrestling: { name: "Tecmo World Wrestling", url: "https://github.com/dientu4nut/NES/blob/master/Tecmo%20World%20Wrestling%20(U)%20.nes" },
    TeenageMutantNinjaTurtles: { name: "Teenage Mutant Ninja Turtles", url: "https://github.com/dientu4nut/NES/blob/master/Teenage%20Mutant%20Ninja%20Turtles%20(U)%20.nes" },
    TeenageMutantNinjaTurtlesTournamentFighters: { name: "Teenage Mutant Ninja Turtles - Tournament Fighters", url: "https://github.com/dientu4nut/NES/blob/master/Teenage%20Mutant%20Ninja%20Turtles%20-%20Tournament%20Fighters%20(U)%20.nes" },
    TeenageMutantNinjaTurtlesIITheArcadeGame: { name: "Teenage Mutant Ninja Turtles II - The Arcade Game", url: "https://github.com/dientu4nut/NES/blob/master/Teenage%20Mutant%20Ninja%20Turtles%20II%20-%20The%20Arcade%20Game%20(U)%20.nes" },
    TeenageMutantNinjaTurtlesIIITheManhattanProject: { name: "Teenage Mutant Ninja Turtles III - The Manhattan Project", url: "https://github.com/dientu4nut/NES/blob/master/Teenage%20Mutant%20Ninja%20Turtles%20III%20-%20The%20Manhattan%20Project%20(U)%20.nes" },
    Terminator2JudgmentDay: { name: "Terminator 2 - Judgment Day", url: "https://github.com/dientu4nut/NES/blob/master/Terminator%202%20-%20Judgment%20Day%20(U)%20.nes" },
    TerminatorThe: { name: "Terminator The", url: "https://github.com/dientu4nut/NES/blob/master/Terminator%20The%20(U)%20.nes" },
    TerraCresta: { name: "Terra Cresta", url: "https://github.com/dientu4nut/NES/blob/master/Terra%20Cresta%20(U)%20.nes" },
    Tetris: { name: "Tetris", url: "https://github.com/dientu4nut/NES/blob/master/Tetris%20(U)%20.nes" },
    Tetris2: { name: "Tetris 2", url: "https://github.com/dientu4nut/NES/blob/master/Tetris%202%20(U)%20.nes" },
    TetrisFamily12in1GS2013U: { name: "Tetris Family 12-in-1 (GS-2013) [U]", url: "https://github.com/dientu4nut/NES/blob/master/Tetris%20Family%2012-in-1%20(GS-2013)%20%5BU%5D.nes" },
    TetrisFamily6in1GS2004U: { name: "Tetris Family 6-in-1 (GS-2004) [U]", url: "https://github.com/dientu4nut/NES/blob/master/Tetris%20Family%206-in-1%20(GS-2004)%20%5BU%5D.nes" },
    ThreeStooges: { name: "Three Stooges", url: "https://github.com/dientu4nut/NES/blob/master/Three%20Stooges%20(U)%20.nes" },
    ThunderLightning: { name: "Thunder & Lightning", url: "https://github.com/dientu4nut/NES/blob/master/Thunder%20%26%20Lightning%20(U)%20.nes" },
    Thunderbirds: { name: "Thunderbirds", url: "https://github.com/dientu4nut/NES/blob/master/Thunderbirds%20(U)%20.nes" },
    Thundercade: { name: "Thundercade", url: "https://github.com/dientu4nut/NES/blob/master/Thundercade%20(U)%20.nes" },
    TigerHeli: { name: "Tiger-Heli", url: "https://github.com/dientu4nut/NES/blob/master/Tiger-Heli%20(U)%20.nes" },
    TimeLord: { name: "Time Lord", url: "https://github.com/dientu4nut/NES/blob/master/Time%20Lord%20(U)%20.nes" },
    TimesofLore: { name: "Times of Lore", url: "https://github.com/dientu4nut/NES/blob/master/Times%20of%20Lore%20(U)%20.nes" },
    TinyToonAdventures: { name: "Tiny Toon Adventures", url: "https://github.com/dientu4nut/NES/blob/master/Tiny%20Toon%20Adventures%20(U)%20.nes" },
    TinyToonAdventures2TroubleinWackyland: { name: "Tiny Toon Adventures 2 - Trouble in Wackyland", url: "https://github.com/dientu4nut/NES/blob/master/Tiny%20Toon%20Adventures%202%20-%20Trouble%20in%20Wackyland%20(U)%20.nes" },
    TinyToonAdventuresCartoonWorkshop: { name: "Tiny Toon Adventures Cartoon Workshop", url: "https://github.com/dientu4nut/NES/blob/master/Tiny%20Toon%20Adventures%20Cartoon%20Workshop%20(U)%20.nes" },
    ToTheEarth: { name: "To The Earth", url: "https://github.com/dientu4nut/NES/blob/master/To%20The%20Earth%20(U)%20.nes" },
    Toki: { name: "Toki", url: "https://github.com/dientu4nut/NES/blob/master/Toki%20(U)%20.nes" },
    TomJerry: { name: "Tom & Jerry", url: "https://github.com/dientu4nut/NES/blob/master/Tom%20%26%20Jerry%20(U)%20.nes" },
    TombsTreasure: { name: "Tombs & Treasure", url: "https://github.com/dientu4nut/NES/blob/master/Tombs%20%26%20Treasure%20(U)%20.nes" },
    TopGunTheSecondMission: { name: "Top Gun - The Second Mission", url: "https://github.com/dientu4nut/NES/blob/master/Top%20Gun%20-%20The%20Second%20Mission%20(U)%20.nes" },
    TopPlayersTennisFeaturingChrisEvertIvanLendl: { name: "Top Players  Tennis - Featuring Chris Evert & Ivan Lendl", url: "https://github.com/dientu4nut/NES/blob/master/Top%20Players%20%20Tennis%20-%20Featuring%20Chris%20Evert%20%26%20Ivan%20Lendl%20(U)%20.nes" },
    TotalRecall: { name: "Total Recall", url: "https://github.com/dientu4nut/NES/blob/master/Total%20Recall%20(U)%20.nes" },
    TotallyRad: { name: "Totally Rad", url: "https://github.com/dientu4nut/NES/blob/master/Totally%20Rad%20(U)%20.nes" },
    TouchDownFever: { name: "Touch Down Fever", url: "https://github.com/dientu4nut/NES/blob/master/Touch%20Down%20Fever%20(U)%20.nes" },
    ToxicCrusaders: { name: "Toxic Crusaders", url: "https://github.com/dientu4nut/NES/blob/master/Toxic%20Crusaders%20(U)%20.nes" },
    TrackField: { name: "Track & Field", url: "https://github.com/dientu4nut/NES/blob/master/Track%20%26%20Field%20(U)%20.nes" },
    TreasureMaster: { name: "Treasure Master", url: "https://github.com/dientu4nut/NES/blob/master/Treasure%20Master%20(U)%20.nes" },
    Trog: { name: "Trog", url: "https://github.com/dientu4nut/NES/blob/master/Trog%20(U)%20.nes" },
    Trojan: { name: "Trojan", url: "https://github.com/dientu4nut/NES/blob/master/Trojan%20(U)%20.nes" },
    TrollsinCrazylandThe: { name: "Trolls in Crazyland The", url: "https://github.com/dientu4nut/NES/blob/master/Trolls%20in%20Crazyland%20The%20(E).nes" },
    TwinCobra: { name: "Twin Cobra", url: "https://github.com/dientu4nut/NES/blob/master/Twin%20Cobra%20(U)%20.nes" },
    TwinEagleRevengeJoesBrother: { name: "Twin Eagle - Revenge Joe s Brother", url: "https://github.com/dientu4nut/NES/blob/master/Twin%20Eagle%20-%20Revenge%20Joe%20s%20Brother%20(U)%20.nes" },
    UfouriaTheSaga: { name: "U-four-ia - The Saga ", url: "https://github.com/dientu4nut/NES/blob/master/U-four-ia%20-%20The%20Saga%20(E)%20.nes" },
    UltimaExodus: { name: "Ultima - Exodus", url: "https://github.com/dientu4nut/NES/blob/master/Ultima%20-%20Exodus%20(U)%20.nes" },
    UltimaQuestoftheAvatar: { name: "Ultima - Quest of the Avatar", url: "https://github.com/dientu4nut/NES/blob/master/Ultima%20-%20Quest%20of%20the%20Avatar%20(U)%20.nes" },
    UltimaWarriorsofDestiny: { name: "Ultima - Warriors of Destiny", url: "https://github.com/dientu4nut/NES/blob/master/Ultima%20-%20Warriors%20of%20Destiny%20(U)%20.nes" },
    UltimateAirCombat: { name: "Ultimate Air Combat", url: "https://github.com/dientu4nut/NES/blob/master/Ultimate%20Air%20Combat%20(U)%20.nes" },
    UltimateBasketball: { name: "Ultimate Basketball", url: "https://github.com/dientu4nut/NES/blob/master/Ultimate%20Basketball%20(U)%20.nes" },
    UncannyXMenThe: { name: "Uncanny X-Men The", url: "https://github.com/dientu4nut/NES/blob/master/Uncanny%20X-Men%20The%20(U)%20.nes" },
    UnchartedWaters: { name: "Uncharted Waters", url: "https://github.com/dientu4nut/NES/blob/master/Uncharted%20Waters%20(U)%20.nes" },
    Uninvited: { name: "Uninvited", url: "https://github.com/dientu4nut/NES/blob/master/Uninvited%20(U)%20.nes" },
    VegasDream: { name: "Vegas Dream", url: "https://github.com/dientu4nut/NES/blob/master/Vegas%20Dream%20(U)%20.nes" },
    ViceProjectDoom: { name: "Vice - Project Doom", url: "https://github.com/dientu4nut/NES/blob/master/Vice%20-%20Project%20Doom%20(U)%20.nes" },
    Videomation: { name: "Videomation", url: "https://github.com/dientu4nut/NES/blob/master/Videomation%20(U)%20.nes" },
    WCWWorldChampionshipWrestling: { name: "WCW World Championship Wrestling", url: "https://github.com/dientu4nut/NES/blob/master/WCW%20World%20Championship%20Wrestling%20(U)%20.nes" },
    WURMJourneytotheCenteroftheEarth: { name: "WURM - Journey to the Center of the Earth", url: "https://github.com/dientu4nut/NES/blob/master/WURM%20-%20Journey%20to%20the%20Center%20of%20the%20Earth%20(U)%20.nes" },
    WWFKingoftheRing: { name: "WWF King of the Ring", url: "https://github.com/dientu4nut/NES/blob/master/WWF%20King%20of%20the%20Ring%20(U)%20.nes" },
    WWFWrestleMania: { name: "WWF WrestleMania", url: "https://github.com/dientu4nut/NES/blob/master/WWF%20WrestleMania%20(U)%20.nes" },
    WWFWrestleManiaSteelCageChallenge: { name: "WWF WrestleMania - Steel Cage Challenge", url: "https://github.com/dientu4nut/NES/blob/master/WWF%20WrestleMania%20-%20Steel%20Cage%20Challenge%20(U)%20.nes" },
    WWFWrestleManiaChallenge: { name: "WWF WrestleMania Challenge", url: "https://github.com/dientu4nut/NES/blob/master/WWF%20WrestleMania%20Challenge%20(U)%20.nes" },
    WackyRaces: { name: "Wacky Races", url: "https://github.com/dientu4nut/NES/blob/master/Wacky%20Races%20(U)%20.nes" },
    WallStreetKid: { name: "Wall Street Kid", url: "https://github.com/dientu4nut/NES/blob/master/Wall%20Street%20Kid%20(U)%20.nes" },
    WariosWoods: { name: "Wario s Woods", url: "https://github.com/dientu4nut/NES/blob/master/Wario%20s%20Woods%20(U)%20.nes" },
    WayneGretzkyHockey: { name: "Wayne Gretzky Hockey", url: "https://github.com/dientu4nut/NES/blob/master/Wayne%20Gretzky%20Hockey%20(U)%20.nes" },
    WaynesWorld: { name: "Wayne s World", url: "https://github.com/dientu4nut/NES/blob/master/Wayne%20s%20World%20(U)%20.nes" },
    WerewolfTheLastWarrior: { name: "Werewolf - The Last Warrior", url: "https://github.com/dientu4nut/NES/blob/master/Werewolf%20-%20The%20Last%20Warrior%20(U)%20.nes" },
    WheelofFortuneStarringVannaWhite: { name: "Wheel of Fortune - Starring Vanna White", url: "https://github.com/dientu4nut/NES/blob/master/Wheel%20of%20Fortune%20-%20Starring%20Vanna%20White%20(U)%20.nes" },
    WheelofFortuneFamilyEdition: { name: "Wheel of Fortune Family Edition", url: "https://github.com/dientu4nut/NES/blob/master/Wheel%20of%20Fortune%20Family%20Edition%20(U)%20.nes" },
    WheelofFortuneJuniorEdition: { name: "Wheel of Fortune Junior Edition", url: "https://github.com/dientu4nut/NES/blob/master/Wheel%20of%20Fortune%20Junior%20Edition%20(U)%20.nes" },
    WhereinTimeisCarmenSandiego: { name: "Where in Time is Carmen Sandiego", url: "https://github.com/dientu4nut/NES/blob/master/Where%20in%20Time%20is%20Carmen%20Sandiego%20(U)%20.nes" },
    WheresWaldo: { name: "Where s Waldo", url: "https://github.com/dientu4nut/NES/blob/master/Where%20s%20Waldo%20(U)%20.nes" },
    WhoFramedRogerRabbit: { name: "Who Framed Roger Rabbit", url: "https://github.com/dientu4nut/NES/blob/master/Who%20Framed%20Roger%20Rabbit%20(U)%20.nes" },
    WhompEm: { name: "Whomp Em", url: "https://github.com/dientu4nut/NES/blob/master/Whomp%20Em%20(U)%20.nes" },
    Widget: { name: "Widget", url: "https://github.com/dientu4nut/NES/blob/master/Widget%20(U)%20.nes" },
    Willow: { name: "Willow", url: "https://github.com/dientu4nut/NES/blob/master/Willow%20(U)%20.nes" },
    WinLoseorDraw: { name: "Win Lose or Draw", url: "https://github.com/dientu4nut/NES/blob/master/Win%20Lose%20or%20Draw%20(U)%20.nes" },
    WizardryProvingGroundsoftheMadOverlord: { name: "Wizardry - Proving Grounds of the Mad Overlord", url: "https://github.com/dientu4nut/NES/blob/master/Wizardry%20-%20Proving%20Grounds%20of%20the%20Mad%20Overlord%20(U)%20.nes" },
    WizardryTheKnightofDiamonds: { name: "Wizardry - The Knight of Diamonds", url: "https://github.com/dientu4nut/NES/blob/master/Wizardry%20-%20The%20Knight%20of%20Diamonds%20(U)%20.nes" },
    WizardsWarriorsIIIKurosVisionsofPower: { name: "Wizards & Warriors III - Kuros - Visions of Power", url: "https://github.com/dientu4nut/NES/blob/master/Wizards%20%26%20Warriors%20III%20-%20Kuros%20-%20Visions%20of%20Power%20(U)%20.nes" },
    Wolverine: { name: "Wolverine", url: "https://github.com/dientu4nut/NES/blob/master/Wolverine%20(U)%20.nes" },
    WorldChamp: { name: "World Champ", url: "https://github.com/dientu4nut/NES/blob/master/World%20Champ%20(U)%20.nes" },
    WorldGames: { name: "World Games", url: "https://github.com/dientu4nut/NES/blob/master/World%20Games%20(U)%20.nes" },
    Xenophobe: { name: "Xenophobe", url: "https://github.com/dientu4nut/NES/blob/master/Xenophobe%20(U)%20.nes" },
    Xevious: { name: "Xevious", url: "https://github.com/dientu4nut/NES/blob/master/Xevious%20(U)%20.nes" },
    Xexyz: { name: "Xexyz", url: "https://github.com/dientu4nut/NES/blob/master/Xexyz%20(U)%20.nes" },
    YoNoid: { name: "Yo  Noid", url: "https://github.com/dientu4nut/NES/blob/master/Yo%20%20Noid%20(U)%20.nes" },
    Yoshi: { name: "Yoshi", url: "https://github.com/dientu4nut/NES/blob/master/Yoshi%20(U)%20.nes" },
    YoshisCookie: { name: "Yoshi s Cookie", url: "https://github.com/dientu4nut/NES/blob/master/Yoshi%20s%20Cookie%20(U)%20.nes" },
    YoungIndianaJonesChroniclesThe: { name: "Young Indiana Jones Chronicles The", url: "https://github.com/dientu4nut/NES/blob/master/Young%20Indiana%20Jones%20Chronicles%20The%20(U)%20.nes" },
    Zanac: { name: "Zanac", url: "https://github.com/dientu4nut/NES/blob/master/Zanac%20(U)%20.nes" },
    ZeldaIITheAdventureofLink: { name: "Zelda II - The Adventure of Link", url: "https://github.com/dientu4nut/NES/blob/master/Zelda%20II%20-%20The%20Adventure%20of%20Link%20(U)%20.nes" },
    ZenIntergalacticNinja: { name: "Zen - Intergalactic Ninja", url: "https://github.com/dientu4nut/NES/blob/master/Zen%20-%20Intergalactic%20Ninja%20(U)%20.nes" },
    ZombieNation: { name: "Zombie Nation", url: "https://github.com/dientu4nut/NES/blob/master/Zombie%20Nation%20(U)%20.nes" }
  },
};

export default config;
